\set ON_ERROR_STOP on
create table public.trigger_acl_fixture (id integer, touched boolean default false);
create function public.apply_direct_nhis_inventory_effect() returns trigger language plpgsql security definer as $$ begin new.touched := true; return new; end $$;
grant execute on function public.apply_direct_nhis_inventory_effect() to anon, authenticated;
create function public.apply_dispensary_nhis_inventory_effect() returns trigger language plpgsql security definer as $$ begin new.touched := true; return new; end $$;
grant execute on function public.apply_dispensary_nhis_inventory_effect() to anon, authenticated;
create function public.assign_nhis_claim_number() returns trigger language plpgsql security definer as $$ begin new.touched := true; return new; end $$;
grant execute on function public.assign_nhis_claim_number() to anon, authenticated;
create function public.enforce_chemical_shop_organization_settings() returns trigger language plpgsql security definer as $$ begin new.touched := true; return new; end $$;
grant execute on function public.enforce_chemical_shop_organization_settings() to anon, authenticated;
create function public.enforce_nhis_claim_medicine_catalog_pricing() returns trigger language plpgsql security definer as $$ begin new.touched := true; return new; end $$;
grant execute on function public.enforce_nhis_claim_medicine_catalog_pricing() to anon, authenticated;
create function public.guard_nhis_inventory_policy_change() returns trigger language plpgsql security definer as $$ begin new.touched := true; return new; end $$;
grant execute on function public.guard_nhis_inventory_policy_change() to anon, authenticated;
create function public.preserve_server_nhis_claim_total() returns trigger language plpgsql security definer as $$ begin new.touched := true; return new; end $$;
grant execute on function public.preserve_server_nhis_claim_total() to anon, authenticated;
create function public.prevent_chemical_shop_restricted_stock_change() returns trigger language plpgsql security definer as $$ begin new.touched := true; return new; end $$;
grant execute on function public.prevent_chemical_shop_restricted_stock_change() to anon, authenticated;
create function public.prevent_chemical_shop_restricted_stock_insert() returns trigger language plpgsql security definer as $$ begin new.touched := true; return new; end $$;
grant execute on function public.prevent_chemical_shop_restricted_stock_insert() to anon, authenticated;
create function public.prevent_chemical_shop_restricted_transaction() returns trigger language plpgsql security definer as $$ begin new.touched := true; return new; end $$;
grant execute on function public.prevent_chemical_shop_restricted_transaction() to anon, authenticated;
create function public.prevent_mca_changes_to_direct_nhis_serving() returns trigger language plpgsql security definer as $$ begin new.touched := true; return new; end $$;
grant execute on function public.prevent_mca_changes_to_direct_nhis_serving() to anon, authenticated;
create function public.quarantine_inventory_after_chemical_shop_conversion() returns trigger language plpgsql security definer as $$ begin new.touched := true; return new; end $$;
grant execute on function public.quarantine_inventory_after_chemical_shop_conversion() to anon, authenticated;
create function public.branch_sync_acl_fixture(text) returns boolean language sql security definer as $$ select false $$;
grant execute on function public.branch_sync_acl_fixture(text) to anon;
create trigger fixture before insert on public.trigger_acl_fixture for each row execute function public.apply_direct_nhis_inventory_effect();
grant usage on schema public to authenticated;
grant insert, select on public.trigger_acl_fixture to authenticated;
\ir ../migrations/20260912183000_restrict_internal_trigger_execution.sql
do $$ declare f regprocedure; begin
f := 'public.apply_direct_nhis_inventory_effect()'::regprocedure; if has_function_privilege('anon',f,'execute') or has_function_privilege('authenticated',f,'execute') then raise exception 'Client grant remains: %',f; end if;
f := 'public.apply_dispensary_nhis_inventory_effect()'::regprocedure; if has_function_privilege('anon',f,'execute') or has_function_privilege('authenticated',f,'execute') then raise exception 'Client grant remains: %',f; end if;
f := 'public.assign_nhis_claim_number()'::regprocedure; if has_function_privilege('anon',f,'execute') or has_function_privilege('authenticated',f,'execute') then raise exception 'Client grant remains: %',f; end if;
f := 'public.enforce_chemical_shop_organization_settings()'::regprocedure; if has_function_privilege('anon',f,'execute') or has_function_privilege('authenticated',f,'execute') then raise exception 'Client grant remains: %',f; end if;
f := 'public.enforce_nhis_claim_medicine_catalog_pricing()'::regprocedure; if has_function_privilege('anon',f,'execute') or has_function_privilege('authenticated',f,'execute') then raise exception 'Client grant remains: %',f; end if;
f := 'public.guard_nhis_inventory_policy_change()'::regprocedure; if has_function_privilege('anon',f,'execute') or has_function_privilege('authenticated',f,'execute') then raise exception 'Client grant remains: %',f; end if;
f := 'public.preserve_server_nhis_claim_total()'::regprocedure; if has_function_privilege('anon',f,'execute') or has_function_privilege('authenticated',f,'execute') then raise exception 'Client grant remains: %',f; end if;
f := 'public.prevent_chemical_shop_restricted_stock_change()'::regprocedure; if has_function_privilege('anon',f,'execute') or has_function_privilege('authenticated',f,'execute') then raise exception 'Client grant remains: %',f; end if;
f := 'public.prevent_chemical_shop_restricted_stock_insert()'::regprocedure; if has_function_privilege('anon',f,'execute') or has_function_privilege('authenticated',f,'execute') then raise exception 'Client grant remains: %',f; end if;
f := 'public.prevent_chemical_shop_restricted_transaction()'::regprocedure; if has_function_privilege('anon',f,'execute') or has_function_privilege('authenticated',f,'execute') then raise exception 'Client grant remains: %',f; end if;
f := 'public.prevent_mca_changes_to_direct_nhis_serving()'::regprocedure; if has_function_privilege('anon',f,'execute') or has_function_privilege('authenticated',f,'execute') then raise exception 'Client grant remains: %',f; end if;
f := 'public.quarantine_inventory_after_chemical_shop_conversion()'::regprocedure; if has_function_privilege('anon',f,'execute') or has_function_privilege('authenticated',f,'execute') then raise exception 'Client grant remains: %',f; end if;
if not has_function_privilege('anon','public.branch_sync_acl_fixture(text)','execute') then raise exception 'Sync grant changed'; end if; end $$;
set role authenticated;
insert into public.trigger_acl_fixture(id) values(1);
do $$ begin if not exists(select 1 from public.trigger_acl_fixture where id=1 and touched) then raise exception 'Trigger stopped firing'; end if; end $$;
reset role;
select 'PASS: grants removed, authenticated insert trigger still fires, sync grant preserved';
