-- Run after 00-setup-reset-and-versions.sql.
-- If this batch was already run and you need to restart, rerun 00 first.

BEGIN;

-- Tariff seed batch 3 of 14. Split so Supabase SQL Editor does not truncate one very large INSERT.
INSERT INTO public.nhia_tariff_items (
  tariff_version, facility_group, catering_option, mdc, gdrg_code, description,
  age_band, tariff_amount, currency, source_file, source_page, is_active, updated_at
)
VALUES
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM04C', 'Change of Catheter <12 Yrs', '<12 Yrs', 20.14, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM05A', 'Change of Dressing >= 12 Yrs', '>= 12 Yrs', 31.00, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM05C', 'Change of Dressing < 12 Yrs', '< 12 Yrs', 31.00, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM06A', 'Male Circumcision >=12 Yrs', '>=12 Yrs', 62.28, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM06C', 'Male Circumcision <12 Yrs', '<12 Yrs', 62.28, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM07A', 'Dressing And Minor Suturing >=12 Yrs', '>=12 Yrs', 80.46, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM07C', 'Dressing And Minor Suturing <=12 Yrs', '<=12 Yrs', 77.25, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM08A', 'Tubal Ligation >=12 Yrs', '>=12 Yrs', 101.00, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM09A', 'Vasectomy >=12 Yrs', '>=12 Yrs', 101.00, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM10A', 'IUD >=12 Yrs', '>=12 Yrs', 11.00, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM11A', 'Implant >=12 Yrs', '>=12 Yrs', 11.00, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM12A', 'Injectable (Three Months) >=12 Yrs', '>=12 Yrs', 5.00, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM13A', 'Injectable (One Month) >=12 Yrs', '>=12 Yrs', 1.67, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC02A', 'Antenatal/Postnatal', NULL, 34.75, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC03A', 'Dental Adult (without procedure)', NULL, 18.99, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC03C', 'Dental Child (without procedure)', NULL, 21.76, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC04A', 'ENT Adult (without procedure)', NULL, 23.36, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC04C', 'ENT Child (without procedure)', NULL, 22.04, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC05A', 'Eye Adult (without procedure)', NULL, 21.75, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC05C', 'Eye Child (without procedure)', NULL, 21.22, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC06A', 'General OPD - Adult', NULL, 21.90, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC06C', 'General OPD - Child', NULL, 22.26, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC11A', 'Unbundled Consultation - Adult', NULL, 23.56, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC11C', 'Unbundled Consultation - Child', NULL, 23.10, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC13A', 'Physiotheraphy-Adult', NULL, 27.96, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC13C', 'Physiotheraphy-Child', NULL, 27.60, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE01D', '2 Hour Post Prandial Blood Glucose', NULL, 19.03, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE01E', 'Serum Adrenocorticotropic Hormone (ACTH)', NULL, 10.61, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE02D', '24 Hr Urine for Protein', NULL, 14.09, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE02E', 'Serum Albumin', NULL, 12.26, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE03D', 'Alanine Aminotransferase (ALT)', NULL, 14.21, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE03E', 'Serum Alkalne Phosphatase (ALP)', NULL, 11.64, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE04D', 'Alpha Amylase (Serum/Urine)', NULL, 18.85, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE04E', 'Serum Beta-Human Chorionic Gonadotropin (HCG)', NULL, 24.51, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE05D', 'Alpha-Fetoprotein (AFP)', NULL, 13.24, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE05E', 'Serum Calcium', NULL, 15.41, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE06D', 'Ap-Prothrombin Time', NULL, 15.98, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE06E', 'Serum Creatinine', NULL, 11.84, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE07D', 'Arterial Blood Gas (ABG)', NULL, 22.74, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE07E', 'Serum Electrolyte (Na+, K+)', NULL, 13.14, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE08D', 'Aspartate Aminotransferase (AST)', NULL, 12.42, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE08E', 'Serum Ferritin', NULL, 22.49, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE09D', 'B/F for Malaria Parasites', NULL, 8.74, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE09E', 'Serum Iron (Fe)', NULL, 12.91, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE100', 'Acid Phosphate', NULL, 11.12, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE101', 'Chloride', NULL, 11.37, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE102', 'Direct Bilirubin/Total Bilirubin', NULL, 14.26, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE103', 'Donor Screening for HB & AG', NULL, 20.77, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE104', 'Grouping/X'' Matching/Unit', NULL, 12.19, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE105', 'Hepatitis C screening', NULL, 11.97, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE106', 'IOPA Xray', NULL, 17.95, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE107', 'Magnesium', NULL, 12.42, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE108', 'NA+', NULL, 11.76, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE109', 'Phosphorus', NULL, 12.44, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE10D', 'Barium Enema', NULL, 165.53, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE10E', 'Serum Lactate Dehydrogenase (LDH)', NULL, 12.91, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE110', 'Platelet Count', NULL, 9.26, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE111', 'Potassium', NULL, 12.44, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE112', 'Renal Function Test', NULL, 20.38, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE113', 'Semen Analysis', NULL, 49.64, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE114', 'Total leucocyte count', NULL, 10.35, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE115', 'Total Proteins Blood', NULL, 9.41, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE116', 'Urine Sugar', NULL, 7.28, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE117', 'VCT', NULL, 3.89, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE118', 'Vitality Test', NULL, 24.12, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE119', 'VLDL', NULL, 9.54, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE11D', 'Barium Meal', NULL, 104.90, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE11E', 'Serum Prolactin (PRL)', NULL, 25.48, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE120', 'WBC+Differential', NULL, 11.86, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE122', 'Malaria Card Test (Dipstik assay/rapid card)', NULL, 4.49, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE123', 'RH Typing', NULL, 9.29, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE124', 'Keratometry', NULL, 15.60, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE125', 'A-scan', NULL, 47.57, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE126', 'Serum vitamin B12, and folate levels', NULL, 99.81, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE129', 'Ultrasound biomicroscopy', NULL, 50.34, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE12D', 'Barium Meal & Follow Through', NULL, 113.25, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE12E', 'Serum Total Protein', NULL, 11.04, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE130', 'Demonstration of Heinz bodies', NULL, 12.78, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE132', 'Anti-streptolysin test', NULL, 21.24, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE133', 'Viral serology', NULL, 102.21, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE134', 'Calcium Infusion test', NULL, 22.89, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE135', 'Pulmonary Function test', NULL, 48.29, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE136', 'Pleural fluid analysis', NULL, 16.78, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE137', 'Cancer antigen 19-9', NULL, 83.54, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE138', 'Transhepatic cholangiography (PTC)', NULL, 110.41, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE139', 'Bone Scan', NULL, 109.58, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE13D', 'Barium Swallow', NULL, 96.13, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE13E', 'Serum Triglyceride', NULL, 11.94, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE140', 'Breast tissue Biopsy', NULL, 30.47, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE141', 'C Reactive Protein', NULL, 19.93, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE142', 'EEG (Electroencephalogram)', NULL, 61.17, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE143', 'Holter', NULL, 101.91, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE145', 'Myocardial perfusion imaging', NULL, 196.10, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE146', 'Guthrie test', NULL, 60.77, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE149', 'Typhi Dot', NULL, 13.63, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE14D', 'Bilirubin', NULL, 12.42, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE14E', 'Serum Uric Acid', NULL, 13.91, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE150', 'AEC', NULL, 13.66, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE151', 'Blood Sugar PP', NULL, 7.52, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE152', 'Biopsy L/A', NULL, 93.50, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE154', 'ASO titre', NULL, 28.27, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE155', 'Gonioscopy', NULL, 12.57, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE156', 'Hematocrit', NULL, 18.08, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE157', 'CT Scan - 2 Region with No Contrast', NULL, 172.08, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE158', 'CT Scan - 2 Region + 1Contrast', NULL, 176.02, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE159', 'CT Scan - 2 region + 2 contrast', NULL, 198.15, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE15D', 'Bleeding and Clotting Time', NULL, 9.76, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE15E', 'Sialogram', NULL, 79.97, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE160', 'MRI 2 region with no contrast', NULL, 390.66, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE161', 'MRI 2 region with + contrast', NULL, 497.30, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE16D', 'Blood for C/S', NULL, 19.90, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE16E', 'Sickling Test', NULL, 7.93, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE17D', 'Blood Grouping', NULL, 10.47, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE17E', 'Skin Scrapping for Fungal Elements', NULL, 8.93, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE18D', 'Blood Grouping & Antibody Screen', NULL, 13.40, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE18E', 'Skin Snip', NULL, 8.96, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE19D', 'Blood Parasites', NULL, 13.19, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE19E', 'Stool C/S', NULL, 19.45, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE20D', 'Blood Urea', NULL, 19.75, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE20E', 'Stool For Occult Blood', NULL, 9.06, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE21D', 'Blood Urea & Electrolytes', NULL, 21.78, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE21E', 'T3', NULL, 48.84, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE22D', 'Bone Marrow - Trephine Biopsy', NULL, 119.04, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE22E', 'T4', NULL, 48.84, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE23D', 'Bone Marrow Aspirate', NULL, 78.65, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE23E', 'Testosterone', NULL, 30.81, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE24D', 'Bue & Creatinine', NULL, 22.89, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE24E', 'Thyroid Function Test (TSH)', NULL, 29.62, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE25D', 'Carcino Embryonic Antigen (CEA)', NULL, 12.00, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE25E', 'Thyroid Profile', NULL, 65.66, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE26D', 'Cerebrospinal Fluid for C/S', NULL, 21.57, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE26E', 'Total Iron Binding Capacity (TIBC)', NULL, 15.26, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE27D', 'Clusters Of Differentiation Cells (CD4)', NULL, 68.83, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE27E', 'Total Serum Cholesterol', NULL, 11.41, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE28D', 'Coombs Test (Direct)', NULL, 13.54, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE28E', 'Trophozoite Count', NULL, 13.78, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE29D', 'Creatine Kinase - Mb (CK - Mb)', NULL, 18.40, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE29E', 'Troponin', NULL, 22.68, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE30D', 'Creatine Kinase (CK)', NULL, 15.41, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE30E', 'Ultrasound', NULL, 37.47, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE31D', 'CSF Latex Agglutination', NULL, 14.36, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE31E', 'Ultrasound - 2 Regions', NULL, 52.43, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE32D', 'CT Scan - 1 Region + 2 Contrast', NULL, 344.20, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE32E', 'Ultrasound Guided Incision & Drainage', NULL, 64.63, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE33D', 'CT Scan - 1 Region + 1IV Contrast', NULL, 276.25, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE33E', 'Urethrogram', NULL, 76.43, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE34D', 'CT Scan - 1 Region + No Contrast', NULL, 99.09, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE34E', 'Urine C/S', NULL, 17.95, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE35D', 'Cystogram', NULL, 96.82, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE35E', 'Urine For Bence Jones Protein', NULL, 7.60, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE36D', 'Cytology', NULL, 21.98, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE36E', 'Veneral Disease Research Laboratory (VDRL)', NULL, 8.03, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE37D', 'Digoxin Level', NULL, 10.61, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE37E', 'Venogram - 1 Region', NULL, 230.58, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE38D', 'Dihydroxy Epiandesterone Sulphate (Dhea-S)', NULL, 11.41, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE38E', 'Widal Test', NULL, 10.41, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE39D', 'Doppler Scan', NULL, 36.85, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE40D', 'Ductologram/Galactographyy', NULL, 75.70, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE41D', 'ECG', NULL, 15.83, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE42D', 'Erythrocyte Sedimentation Rate (ESR)', NULL, 7.93, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE43D', 'Estrogen', NULL, 23.94, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE44D', 'Factor IX', NULL, 29.62, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE45D', 'Factor VIII', NULL, 64.78, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE46D', 'Fasting Blood Sugar/Random Blood Sugar', NULL, 8.95, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE47D', 'Fistulogram', NULL, 134.09, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE48D', 'Follicle Stimulating Hormone (FSH)', NULL, 25.73, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE49D', 'FT3', NULL, 29.55, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE50D', 'FT4', NULL, 29.55, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE51D', 'Full Blood Count FBC (Auto) & Film Comment', NULL, 21.69, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE52D', 'Full Blood Count FBC (Automation)', NULL, 18.60, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE53D', 'Full Blood Count With Film Comment (Manual)', NULL, 21.02, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE54D', 'Fungal Cultures', NULL, 21.39, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE55D', 'Gamma Glutamyl Transferase (GGT)', NULL, 18.40, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE56D', 'Glucose-6-Phosphate Dehydrogenase (G6PD)', NULL, 12.42, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE57D', 'Glycosylated Haemoglobin (HBA 1C)', NULL, 25.13, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE58D', 'Haemoglobin A2 & F Estimation', NULL, 12.39, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE59D', 'Haemoglobin Electrophoresis', NULL, 14.71, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE60D', 'Haemoglobin Estimation (HB)', NULL, 9.07, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE61D', 'HDL - Cholesterol', NULL, 14.21, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE62D', 'Helicobacter Pylori Test', NULL, 9.60, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE63D', 'Hepatitis B Surface Antigen (HBSAG) HBV', NULL, 9.94, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE64D', 'Hepatitis B Virus Profile (HBV Profile)', NULL, 22.41, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE65D', 'High Vaginal Swab for C/S', NULL, 19.30, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE66D', 'High Vaginal Swab Routine Examination', NULL, 11.10, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE67D', 'Histopathology', NULL, 37.19, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE68D', 'Human Immunodeficiency Virus (HIV) Confirmation', NULL, 19.15, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE69D', 'Human Immunodeficiency Virus (HIV) Screening', NULL, 17.35, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE70D', 'Hysterosalpingogram', NULL, 61.39, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE71D', 'Immunostaining', NULL, 69.26, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE72D', 'Intravenous Urography', NULL, 256.59, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE73D', 'LDL - Cholesterol', NULL, 12.78, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE74D', 'LFT', NULL, 29.84, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE75D', 'Lipid Profile', NULL, 28.32, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE76D', 'Lupus Erythematosus Cell (Le Cell)', NULL, 15.41, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE77D', 'Luteinizing Hormone (LH)', NULL, 25.46, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE78D', 'Mammogram', NULL, 54.73, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE79D', 'Miscelllaneous Cultures (Fluids, Aspirates & Exudates)', NULL, 17.65, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE80D', 'MRI - 1 Region + Contrast', NULL, 359.41, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE81D', 'MRI - 1 Region + No Contrast', NULL, 165.52, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'CHAG Primary Care Hospital', 'exclusive', 'Investigation', 'INVE82D', 'Myelogram - 1 Region', NULL, 111.60, 'GHS', 'CHAG Primary Hospital (Catering Exclusive).pdf', 38, true, NOW());

COMMIT;
