-- Run after 00-setup-reset-and-versions.sql.
-- If this batch was already run and you need to restart, rerun 00 first.

BEGIN;

-- Tariff seed batch 9 of 14. Split so Supabase SQL Editor does not truncate one very large INSERT.
INSERT INTO public.nhia_tariff_items (
  tariff_version, facility_group, catering_option, mdc, gdrg_code, description,
  age_band, tariff_amount, currency, source_file, source_page, is_active, updated_at
)
VALUES
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR02C', 'Shaving and Skin Grafting <12 Yrs', '<12 Yrs', 970.08, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 24, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR03A', 'Excisional Debridement and Dressing >=12 Yrs', '>=12 Yrs', 783.07, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 24, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR03C', 'Excisional Debridement and Dressing <12 Yrs', '<12 Yrs', 739.40, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR04A', 'Excisional Debridement with Suturing >=12 Yrs', '>=12 Yrs', 486.77, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR04C', 'Excisional Debridement with Suturing <12 Yrs', '<12 Yrs', 431.06, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR05A', 'Excisional Debridement with Skin Grafting >=12 Yrs', '>=12 Yrs', 746.24, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR05C', 'Excisional Debridement with Skin Grafting <12 Yrs', '<12 Yrs', 705.05, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR06A', 'Excisional Debridement with Flap Reconstruction >=12 Yrs', '>=12 Yrs', 877.37, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR06C', 'Excisional Debridement with Flap Reconstruction <12 Yrs', '<12 Yrs', 798.82, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR07A', 'Excision Biopsy >=12 Yrs', '>=12 Yrs', 310.13, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR07C', 'Excision Biopsy <12 Yrs', '<12 Yrs', 291.66, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR08A', 'Escharotomy >=12 Yrs', '>=12 Yrs', 852.61, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR08C', 'Escharotomy <12 Yrs', '<12 Yrs', 816.42, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR09A', 'Z-plasty >=12 Yrs', '>=12 Yrs', 596.84, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR09C', 'Z-plasty <12 Yrs', '<12 Yrs', 560.23, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR10A', 'Corrective Osteotomy >=12 Yrs', '>=12 Yrs', 1119.95, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR10C', 'Corrective Osteotomy <12 Yrs', '<12 Yrs', 1013.40, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR11A', 'Reconstruction >=12 Yrs', '>=12 Yrs', 637.25, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR11C', 'Reconstruction <12 Yrs', '<12 Yrs', 586.80, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR12A', 'Release/Excision and Split Skin Grafting >=12 Yrs', '>=12 Yrs', 756.58, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR12C', 'Release/Excision and Split Skin Grafting <12 Yrs', '<12 Yrs', 674.81, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR13A', 'Release/Excision and Full thickness skin graft >=12 Yrs', '>=12 Yrs', 806.95, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR13C', 'Release/Excision and Full thickness skin graft <12 Yrs', '<12 Yrs', 754.92, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR14A', 'Debaulking >=12 Yrs', '>=12 Yrs', 1065.58, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR14C', 'Debaulking <12 Yrs', '<12 Yrs', 1003.42, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR15A', 'Primary Suturing >=12 Yrs', '>=12 Yrs', 492.43, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Reconstructive Surgery', 'RSUR15C', 'Primary Suturing <12 Yrs', '<12 Yrs', 462.54, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM01A', 'Endoscopy (Rigid & Flexible) >=12 Yrs', '>=12 Yrs', 158.64, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM01C', 'Endoscopy (Rigid & Flexible) <12 Yrs', '<12 Yrs', 149.37, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM02A', 'Detention for Observation and Treatment - Adult', NULL, 46.32, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM02C', 'Detention for Observation and Treatment - Child', NULL, 34.97, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM03A', 'Inpatient transfer out/Referral- Adult', NULL, 108.54, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM03C', 'Inpatient transfer out/Referral- Child', NULL, 101.03, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM04A', 'Change of Catheter >= 12 Yrs', '>= 12 Yrs', 21.05, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM04C', 'Change of Catheter <12 Yrs', '<12 Yrs', 21.05, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM05A', 'Change of Dressing >= 12 Yrs', '>= 12 Yrs', 32.55, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM05C', 'Change of Dressing < 12 Yrs', '< 12 Yrs', 32.55, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM06A', 'Male Circumcision >=12 Yrs', '>=12 Yrs', 57.60, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM06C', 'Male Circumcision <12 Yrs', '<12 Yrs', 57.60, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM07A', 'Dressing And Minor Suturing >=12 Yrs', '>=12 Yrs', 81.59, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM07C', 'Dressing And Minor Suturing <=12 Yrs', '<=12 Yrs', 78.97, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM08A', 'Tubal Ligation', NULL, 110.00, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM09A', 'Vasectomy', NULL, 110.00, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM10A', 'IUD >=12 Yrs', '>=12 Yrs', 12.00, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM11A', 'Implant >=12 Yrs', '>=12 Yrs', 12.00, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM12A', 'Injectable (Three Months) >=12 Yrs', '>=12 Yrs', 6.00, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Zoom', 'ZOOM13A', 'Injectable (One Month) >=12 Yrs', '>=12 Yrs', 2.00, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC02A', 'Antenatal/Postnatal', NULL, 37.08, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC03A', 'Dental Adult (without procedure)', NULL, 25.21, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC03C', 'Dental Child (without procedure)', NULL, 25.71, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC04A', 'ENT Adult (without procedure)', NULL, 30.16, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC04C', 'ENT Child (without procedure)', NULL, 28.84, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC05A', 'Eye Adult (without procedure)', NULL, 28.55, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC05C', 'Eye Child (without procedure)', NULL, 28.02, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC06A', 'General OPD - Adult', NULL, 28.70, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC06C', 'General OPD - Child', NULL, 29.06, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC11A', 'Unbundled Consultation - Adult', NULL, 23.56, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC11C', 'Unbundled Consultation - Child', NULL, 23.10, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC13A', 'Physiotheraphy-Adult', NULL, 27.96, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Out Patient', 'OPDC13C', 'Physiotheraphy-Child', NULL, 27.60, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE01D', '2 Hour Post Prandial Blood Glucose', NULL, 19.59, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE02D', '24hr Urine for Protein', NULL, 14.50, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE100', 'Acid Phosphate', NULL, 11.44, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE150', 'AEC', NULL, 14.06, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE03D', 'Alanine Aminotransferase (ALT)', NULL, 14.63, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE04D', 'Alpha Amylase (Serum/Urine)', NULL, 19.40, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE05D', 'Alpha-Fetoprotein (AFP)', NULL, 13.63, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE132', 'Anti-streptolysin test', NULL, 21.87, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE06D', 'Ap-Prothrombin Time', NULL, 16.45, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE07D', 'Arterial Blood Gas (ABG)', NULL, 23.41, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE125', 'A-scan', NULL, 48.97, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE154', 'ASO titre', NULL, 29.11, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE08D', 'Aspartate Aminotransferase (AST)', NULL, 12.78, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE09D', 'B/F for Malaria Parasites', NULL, 8.99, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE10D', 'Barium Enema', NULL, 170.40, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE11D', 'Barium Meal', NULL, 107.98, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE12D', 'Barium Meal & Follow Through', NULL, 116.58, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE13D', 'Barium Swallow', NULL, 98.96, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE14D', 'Bilirubin', NULL, 12.78, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE152', 'Biopsy L/A', NULL, 96.25, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE15D', 'Bleeding and Clotting Time', NULL, 10.05, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE16D', 'Blood for C/S', NULL, 20.48, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE17D', 'Blood Grouping', NULL, 10.78, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE18D', 'Blood Grouping & Antibody Screen', NULL, 13.80, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE19D', 'Blood Parasites', NULL, 13.58, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE151', 'Blood Sugar PP', NULL, 7.75, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE20D', 'Blood Urea', NULL, 20.33, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE21D', 'Blood Urea & Electrolytes', NULL, 22.42, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE22D', 'Bone Marrow - Trephine Biopsy', NULL, 122.55, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE23D', 'Bone Marrow Aspirate', NULL, 80.97, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE139', 'Bone Scan', NULL, 112.81, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE140', 'Breast tissue Biopsy', NULL, 31.37, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE24D', 'Bue & Creatinine', NULL, 23.56, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE141', 'C Reactive Protein', NULL, 20.51, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE134', 'Calcium Infusion test', NULL, 23.56, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE137', 'Cancer antigen 19-9', NULL, 85.99, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE25D', 'Carcino Embryonic Antigen (CEA)', NULL, 12.35, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE26D', 'Cerebrospinal Fluid For C/S', NULL, 22.21, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE101', 'Chloride', NULL, 11.70, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE27D', 'Clusters of Differentiation Cells (CD4)', NULL, 70.86, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE28D', 'Coombs Test (Direct)', NULL, 13.94, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE29D', 'Creatine Kinase - Mb (CK - Mb)', NULL, 18.94, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE30D', 'Creatine Kinase (CK)', NULL, 15.86, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE31D', 'CSF Latex Agglutination', NULL, 14.78, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE33D', 'CT Scan - 1 Region + 1IV Contrast', NULL, 284.38, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE32D', 'CT Scan - 1 Region + 2 Contrast', NULL, 354.32, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE34D', 'CT Scan - 1 Region + No Contrast', NULL, 102.01, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE158', 'CT Scan - 2 Region + 1Contrast', NULL, 181.20, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE159', 'CT Scan - 2 region + 2 contrast', NULL, 203.97, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE157', 'CT Scan - 2 Region with No Contrast', NULL, 177.14, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE35D', 'Cystogram', NULL, 99.66, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE36D', 'Cytology', NULL, 22.62, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE130', 'Demonstration of Heinz bodies', NULL, 13.15, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE37D', 'Digoxin Level', NULL, 10.92, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE38D', 'Dihydroxy Epiandesterone Sulphate (Dhea-S)', NULL, 11.75, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE102', 'Direct Bilirubin/Total Bilirubin', NULL, 14.68, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE103', 'Donor Screening for HB & AG', NULL, 21.38, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE39D', 'Doppler Scan', NULL, 37.93, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE40D', 'Ductologram/Galactographyy', NULL, 77.92, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE41D', 'ECG', NULL, 16.30, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE142', 'EEG (Electroencephalogram)', NULL, 62.97, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE42D', 'Erythrocyte Sedimentation Rate (ESR)', NULL, 8.16, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE43D', 'Estrogen', NULL, 24.64, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE44D', 'Factor IX', NULL, 30.49, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE45D', 'Factor VIII', NULL, 66.68, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE46D', 'Fasting Blood Sugar/Random Blood Sugar', NULL, 9.21, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE47D', 'Fistulogram', NULL, 138.03, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE48D', 'Follicle Stimulating Hormone (FSH)', NULL, 26.49, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE49D', 'FT3', NULL, 30.42, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE50D', 'FT4', NULL, 30.42, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE51D', 'Full Blood Count FBC (Auto) & Film Comment', NULL, 22.33, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE52D', 'Full Blood Count FBC (Automation)', NULL, 19.14, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE53D', 'Full Blood Count With Film Comment (Manual)', NULL, 21.64, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE54D', 'Fungal Cultures', NULL, 22.02, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE55D', 'Gamma Glutamyl Transferase (GGT)', NULL, 18.94, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE56D', 'Glucose-6-Phosphate Dehydrogenase (G6PD)', NULL, 12.78, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE57D', 'Glycosylated Haemoglobin (HBA 1C)', NULL, 25.87, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE155', 'Gonioscopy', NULL, 12.94, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE104', 'Grouping/X'' Matching/Unit', NULL, 12.55, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE146', 'Guthrie test', NULL, 62.55, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE58D', 'Haemoglobin A2 & F Estimation', NULL, 12.75, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE59D', 'Haemoglobin Electrophoresis', NULL, 15.15, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE60D', 'Haemoglobin Estimation (HB)', NULL, 9.34, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE61D', 'HDL - Cholesterol', NULL, 14.63, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE62D', 'Helicobacter Pylori Test', NULL, 9.88, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE156', 'Hematocrit', NULL, 18.61, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE63D', 'Hepatitis B Surface Antigen (HBSAG) HBV', NULL, 10.23, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE64D', 'Hepatitis B Virus Profile (HBV Profile)', NULL, 23.07, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE105', 'Hepatitis C screening', NULL, 12.32, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE65D', 'High Vaginal Swab for C/S', NULL, 19.87, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE66D', 'High Vaginal Swab Routine Examination', NULL, 11.43, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE67D', 'Histopathology', NULL, 38.28, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE143', 'Holter', NULL, 104.90, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE68D', 'Human Immunodeficiency Virus (HIV) Confirmation', NULL, 19.71, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE69D', 'Human Immunodeficiency Virus (HIV) Screening', NULL, 17.86, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE70D', 'Hysterosalpingogram', NULL, 63.19, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE71D', 'Immunostaining', NULL, 71.30, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE72D', 'Intravenous Urography', NULL, 264.14, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE106', 'IOPA Xray', NULL, 18.48, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE124', 'Keratometry', NULL, 16.06, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE73D', 'LDL - Cholesterol', NULL, 13.15, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE74D', 'LFT', NULL, 30.72, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE75D', 'Lipid Profile', NULL, 29.15, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE76D', 'Lupus Erythematosus Cell (Le Cell)', NULL, 15.86, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE77D', 'Luteinizing Hormone (LH)', NULL, 26.21, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE107', 'Magnesium', NULL, 12.78, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE122', 'Malaria Card Test (Dipstik assay/rapid card)', NULL, 4.62, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE78D', 'Mammogram', NULL, 56.34, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE79D', 'Miscelllaneous Cultures (Fluids, Aspirates & Exudates)', NULL, 18.17, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE80D', 'MRI - 1 Region + Contrast', NULL, 369.99, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE81D', 'MRI - 1 Region + No Contrast', NULL, 170.39, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE161', 'MRI 2 region with + contrast', NULL, 511.93, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE160', 'MRI 2 region with no contrast', NULL, 402.15, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE82D', 'Myelogram - 1 Region', NULL, 114.88, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE145', 'Myocardial perfusion imaging', NULL, 201.86, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE108', 'NA+', NULL, 12.10, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE83D', 'Oral Glucose Tolerance Test (OGTT)', NULL, 24.24, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE84D', 'Orthopanthomograph (OPT)', NULL, 52.64, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE85D', 'Pancreatic Amylase', NULL, 17.07, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE86D', 'Pap Smear/Fine Needle Aspiration', NULL, 31.25, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE87D', 'Percutaneous Biopsy - CT Scan Guide', NULL, 120.86, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE88D', 'Percutaneous Biopsy - Flouroscopic Guide', NULL, 95.36, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE109', 'Phosphorus', NULL, 12.80, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE91D', 'Plasma Cortisol', NULL, 11.18, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE110', 'Platelet Count', NULL, 9.53, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE136', 'Pleural fluid analysis', NULL, 17.27, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE111', 'Potassium', NULL, 12.80, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE92D', 'Pregnancy Test', NULL, 10.49, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE93D', 'Progesterone (Prog)', NULL, 26.62, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE94D', 'Prostate Specific Antigen (PSA)', NULL, 28.18, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE95D', 'Prothrombin Time', NULL, 15.46, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE135', 'Pulmonary Function test', NULL, 49.71, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE112', 'Renal Function Test', NULL, 20.98, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE96D', 'Reticulocyte Count (Retics)', NULL, 9.61, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE123', 'RH Typing', NULL, 9.56, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE97D', 'Rheumatoid Factor', NULL, 8.19, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE98D', 'Routine Stool Examination', NULL, 7.83, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE99D', 'Routine Urine Examination', NULL, 8.45, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE113', 'Semen Analysis', NULL, 51.10, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'exclusive', 'Investigation', 'INVE01E', 'Serum Adrenocorticotropic Hormone (ACTH)', NULL, 10.92, 'GHS', 'Private Primary Care (Catering Exclusive).pdf', 36, true, NOW());

COMMIT;
