-- Run after 00-setup-reset-and-versions.sql.
-- If this batch was already run and you need to restart, rerun 00 first.

BEGIN;

-- Tariff seed batch 12 of 14. Split so Supabase SQL Editor does not truncate one very large INSERT.
INSERT INTO public.nhia_tariff_items (
  tariff_version, facility_group, catering_option, mdc, gdrg_code, description,
  age_band, tariff_amount, currency, source_file, source_page, is_active, updated_at
)
VALUES
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Paediatric Surgery', 'PSUR25C', 'Posterior Sagittal Anorectoplasty (PSARP) <12 Yrs', '<12 Yrs', 1058.29, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 23, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Paediatric Surgery', 'PSUR26C', 'Burns - OPD Wound Dressing <12 Yrs', '<12 Yrs', 463.72, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 24, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Paediatric Surgery', 'PSUR27C', 'Burns - Non operative Management - Inpatient <12 Yrs', '<12 Yrs', 1642.93, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 24, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Paediatric Surgery', 'PSUR28C', 'Surgery for Burns <12 Yrs', '<12 Yrs', 1541.46, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 24, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Paediatric Surgery', 'PSUR29C', 'Minor Surgery for Sexual Assault <12 Yrs', '<12 Yrs', 489.69, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 24, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Paediatric Surgery', 'PSUR30C', 'Major Surgery for Sexual Assault <12 Yrs', '<12 Yrs', 1017.54, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 24, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Paediatric Surgery', 'PSUR31C', 'Laparotomy with anastomosis <12 Yrs', '<12 Yrs', 1049.18, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 24, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Paediatric Surgery', 'PSUR33C', 'Endoscopic surgery for bleeding oesophageal varices <12 Yrs', '<12 Yrs', 537.42, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 24, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Paediatric Surgery', 'PSUR34C', 'Thoracostomy and chest tube insertion <12 Yrs', '<12 Yrs', 460.07, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 24, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Paediatric Surgery', 'PSUR35C', 'Vascular Surgery Operations <12 Yrs', '<12 Yrs', 1377.00, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 24, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Paediatric Surgery', 'PSUR36C', 'Conservative management of surgery', NULL, 324.45, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 24, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Paediatric Surgery', 'PSUR37C', 'Surgery for removal of finger/toe <12 Yrs', '<12 Yrs', 409.86, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 24, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Paediatric Surgery', 'PSUR38C', 'Surgery for amputation of hand or foot (through or below ankle or wrist joint) <12 Yrs', '<12 Yrs', 652.98, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 24, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Paediatric Surgery', 'PSUR39C', 'Amputation below or through elbow or knee, through proximal joints or for the complete removal of limb <12 Yrs', '<12 Yrs', 874.91, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 24, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR01A', 'Reconstructive repair >=12 Yrs', '>=12 Yrs', 838.94, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 24, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR01C', 'Reconstructive repair <12 Yrs', '<12 Yrs', 800.53, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 24, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR02A', 'Shaving and Skin Grafting >=12 Yrs', '>=12 Yrs', 1330.12, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR02C', 'Shaving and Skin Grafting <12 Yrs', '<12 Yrs', 1310.12, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR03A', 'Excisional Debridement and Dressing >=12 Yrs', '>=12 Yrs', 1133.78, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR03C', 'Excisional Debridement and Dressing <12 Yrs', '<12 Yrs', 1100.93, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR04A', 'Excisional Debridement with Suturing >=12 Yrs', '>=12 Yrs', 634.13, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR04C', 'Excisional Debridement with Suturing <12 Yrs', '<12 Yrs', 500.94, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR05A', 'Excisional Debridement with Skin Grafting >=12 Yrs', '>=12 Yrs', 1019.62, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR05C', 'Excisional Debridement with Skin Grafting <12 Yrs', '<12 Yrs', 996.95, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR06A', 'Excisional Debridement with Flap Reconstruction >=12 Yrs', '>=12 Yrs', 1173.51, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR06C', 'Excisional Debridement with Flap Reconstruction <12 Yrs', '<12 Yrs', 1129.13, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR07A', 'Excision Biopsy >=12 Yrs', '>=12 Yrs', 332.40, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR07C', 'Excision Biopsy <12 Yrs', '<12 Yrs', 314.41, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR08A', 'Escharotomy >=12 Yrs', '>=12 Yrs', 1037.61, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR08C', 'Escharotomy <12 Yrs', '<12 Yrs', 1001.85, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR09A', 'Z-plasty >=12 Yrs', '>=12 Yrs', 729.56, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR09C', 'Z-plasty <12 Yrs', '<12 Yrs', 700.91, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR10A', 'Corrective Osteotomy >=12 Yrs', '>=12 Yrs', 1336.88, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR10C', 'Corrective Osteotomy <12 Yrs', '<12 Yrs', 1257.35, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 25, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR11A', 'Reconstruction >=12 Yrs', '>=12 Yrs', 741.66, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR11C', 'Reconstruction <12 Yrs', '<12 Yrs', 718.08, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR12A', 'Release/Excision and Split Skin Grafting >=12 Yrs', '>=12 Yrs', 925.36, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR12C', 'Release/Excision and Split Skin Grafting <12 Yrs', '<12 Yrs', 860.34, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR13A', 'Release/Excision and Full thickness skin graft >=12 Yrs', '>=12 Yrs', 1065.38, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR13C', 'Release/Excision and Full thickness skin graft <12 Yrs', '<12 Yrs', 1007.38, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR14A', 'Debaulking >=12 Yrs', '>=12 Yrs', 1354.68, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR14C', 'Debaulking <12 Yrs', '<12 Yrs', 1298.69, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR15A', 'Primary Suturing >=12 Yrs', '>=12 Yrs', 655.50, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Reconstructive Surgery', 'RSUR15C', 'Primary Suturing <12 Yrs', '<12 Yrs', 562.29, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM01A', 'Endoscopy (Rigid & Flexible) >=12 Yrs', '>=12 Yrs', 158.64, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM01C', 'Endoscopy (Rigid & Flexible) <12 Yrs', '<12 Yrs', 149.37, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM02A', 'Detention for Observation and Treatment - Adult', NULL, 46.32, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM02C', 'Detention for Observation and Treatment - Child', NULL, 34.97, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM03A', 'Inpatient transfer out/Referral- Adult', NULL, 108.54, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 26, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM03C', 'Inpatient transfer out/Referral- Child', NULL, 101.03, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM04A', 'Change of Catheter >=12 Yrs', '>=12 Yrs', 21.05, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM04C', 'Change of Catheter < 12 Yrs', '< 12 Yrs', 21.05, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM05A', 'Change of Dressing >=12 Yrs', '>=12 Yrs', 32.55, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM05C', 'Change of Dressing < 12 Yrs', '< 12 Yrs', 32.55, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM06A', 'Male Circumcision >=12 Yrs', '>=12 Yrs', 112.10, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM06C', 'Male Circumcision <12 Yrs', '<12 Yrs', 112.10, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM07A', 'Dressing And Minor Suturing >=12 Yrs', '>=12 Yrs', 81.59, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM07C', 'Dressing And Minor Suturing <=12 Yrs', '<=12 Yrs', 78.97, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM08A', 'Tubal Ligation', NULL, 110.00, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM09A', 'Vasectomy', NULL, 110.00, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM10A', 'IUD >=12 Yrs', '>=12 Yrs', 12.00, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM11A', 'Implant >=12 Yrs', '>=12 Yrs', 12.00, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM12A', 'Injectable (Three Months) >=12 Yrs', '>=12 Yrs', 6.00, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Zoom', 'ZOOM13A', 'Injectable (One Month) >=12 Yrs', '>=12 Yrs', 2.00, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 27, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Out Patient', 'OPDC02A', 'G-DRG OUT PATIENT (GH₵) Antenatal/Postnatal', NULL, 37.08, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Out Patient', 'OPDC03A', 'Dental Adult (without procedure)', NULL, 25.21, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Out Patient', 'OPDC03C', 'Dental Child (without procedure)', NULL, 25.71, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Out Patient', 'OPDC04A', 'ENT Adult (without procedure)', NULL, 30.16, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Out Patient', 'OPDC04C', 'ENT Child (without procedure)', NULL, 28.84, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Out Patient', 'OPDC05A', 'Eye Adult (without procedure)', NULL, 28.55, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Out Patient', 'OPDC05C', 'Eye Child (without procedure)', NULL, 28.02, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Out Patient', 'OPDC06A', 'General OPD - Adult', NULL, 28.70, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Out Patient', 'OPDC06C', 'General OPD - Child', NULL, 29.06, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Out Patient', 'OPDC11A', 'Unbundled Consultation - Adult', NULL, 23.56, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Out Patient', 'OPDC11C', 'Unbundled Consultation - Child', NULL, 23.10, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Out Patient', 'OPDC13A', 'Physiotherapy-Adult', NULL, 27.96, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Out Patient', 'OPDC13C', 'Physiotherapy-Child', NULL, 27.60, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 28, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE01D', '2 Hour Post Prandial Blood Glucose', NULL, 19.59, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE02D', '24hr Urine for Protein', NULL, 14.50, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE100', 'Acid Phosphate', NULL, 11.44, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE150', 'AEC', NULL, 14.06, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE03D', 'Alanine Aminotransferase (ALT)', NULL, 14.63, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE04D', 'Alpha Amylase (Serum/Urine)', NULL, 19.40, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE05D', 'Alpha-Fetoprotein (AFP)', NULL, 13.63, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE132', 'Anti-streptolysin test', NULL, 21.87, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE06D', 'Ap-Prothrombin Time', NULL, 16.45, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE07D', 'Arterial Blood Gas (ABG)', NULL, 23.41, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE125', 'A-scan', NULL, 48.97, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE154', 'ASO titre', NULL, 29.11, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE08D', 'Aspartate Aminotransferase (AST)', NULL, 12.78, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE09D', 'B/F for Malaria Parasites', NULL, 8.99, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE10D', 'Barium Enema', NULL, 170.40, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE11D', 'Barium Meal', NULL, 107.98, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE12D', 'Barium Meal & Follow Through', NULL, 116.58, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 29, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE13D', 'Barium Swallow', NULL, 98.96, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE14D', 'Bilirubin', NULL, 12.78, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE152', 'Biopsy L/A', NULL, 96.25, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE15D', 'Bleeding Aand Clotting Time', NULL, 10.05, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE16D', 'Blood for C/S', NULL, 20.48, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE17D', 'Blood Grouping', NULL, 10.78, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE18D', 'Blood Grouping & Antibody Screen', NULL, 13.80, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE19D', 'Blood Parasites', NULL, 13.58, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE151', 'Blood Sugar PP', NULL, 7.75, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE20D', 'Blood Urea', NULL, 20.33, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE21D', 'Blood Urea & Electrolytes', NULL, 22.42, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE22D', 'Bone Marrow - Trephine Biopsy', NULL, 122.55, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE23D', 'Bone Marrow Aspirate', NULL, 80.97, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE139', 'Bone Scan', NULL, 112.81, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE140', 'Breast tissue Biopsy', NULL, 31.37, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE24D', 'Bue & Creatinine', NULL, 23.56, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE141', 'C Reactive Protein', NULL, 20.51, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE134', 'Calcium Infusion test', NULL, 23.56, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 30, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE137', 'Cancer antigen 19-9', NULL, 85.99, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE25D', 'Carcino Embryonic Antigen (CEA)', NULL, 12.35, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE26D', 'Cerebrospinal Fluid for C/S', NULL, 22.21, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE101', 'Chloride', NULL, 11.70, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE27D', 'Clusters of Differentiation Cells (CD4)', NULL, 70.86, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE28D', 'Coombs Test (Direct)', NULL, 13.94, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE29D', 'Creatine Kinase - Mb (CK - Mb)', NULL, 18.94, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE30D', 'Creatine Kinase (CK)', NULL, 15.86, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE31D', 'CSF Latex Agglutination', NULL, 14.78, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE33D', 'CT Scan - 1 Region + 1IV Contrast', NULL, 284.38, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE32D', 'CT Scan - 1 Region + 2 Contrast', NULL, 354.32, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE34D', 'CT Scan - 1 Region + No Contrast', NULL, 102.01, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE158', 'CT Scan - 2 Region + 1Contrast', NULL, 181.20, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE159', 'CT Scan - 2 region + 2 contrast', NULL, 203.97, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE157', 'CT Scan - 2 Region with No Contrast', NULL, 177.14, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE35D', 'Cystogram', NULL, 99.66, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE36D', 'Cytology', NULL, 22.62, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE130', 'Demonstration of Heinz bodies', NULL, 13.15, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 31, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE37D', 'Digoxin Level', NULL, 10.92, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE38D', 'Dihydroxy Epiandesterone Sulphate (Dhea-S)', NULL, 11.75, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE102', 'Direct Bilirubin/Total Bilirubin', NULL, 14.68, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE103', 'Donor Screening for HB & AG', NULL, 21.38, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE39D', 'Doppler Scan', NULL, 37.93, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE40D', 'Ductologram/Galactographyy', NULL, 77.92, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE41D', 'ECG', NULL, 16.30, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE142', 'EEG (Electroencephalogram)', NULL, 62.97, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE42D', 'Erythrocyte Sedimentation Rate (ESR)', NULL, 8.16, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE43D', 'Estrogen', NULL, 24.64, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE44D', 'Factor IX', NULL, 30.49, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE45D', 'Factor VIII', NULL, 66.68, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE46D', 'Fasting Blood Sugar/Random Blood Sugar', NULL, 9.21, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE47D', 'Fistulogram', NULL, 138.03, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE48D', 'Follicle Stimulating Hormone (FSH)', NULL, 26.49, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE49D', 'FT3', NULL, 30.42, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE50D', 'FT4', NULL, 30.42, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE51D', 'Full Blood Count FBC (Auto) & Film Comment', NULL, 22.33, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 32, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE52D', 'Full Blood Count FBC (Automation)', NULL, 19.14, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE53D', 'Full Blood Count With Film Comment (Manual)', NULL, 21.64, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE54D', 'Fungal Cultures', NULL, 22.02, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE55D', 'Gamma Glutamyl Transferase (GGT)', NULL, 18.94, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE56D', 'Glucose-6-Phosphate Dehydrogenase (G6PD)', NULL, 12.78, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE57D', 'Glycosylated Haemoglobin (HBA 1C)', NULL, 25.87, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE155', 'Gonioscopy', NULL, 12.94, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE104', 'Grouping/X'' Matching/Unit', NULL, 12.55, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE146', 'Guthrie test', NULL, 62.55, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE58D', 'Haemoglobin A2 & F Estimation', NULL, 12.75, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE59D', 'Haemoglobin Electrophoresis', NULL, 15.15, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE60D', 'Haemoglobin Estimation (HB)', NULL, 9.34, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE61D', 'HDL - Cholesterol', NULL, 14.63, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE62D', 'Helicobacter Pylori Test', NULL, 9.88, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE156', 'Hematocrit', NULL, 18.61, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE63D', 'Hepatitis B Surface Antigen (HBSAG) HBV', NULL, 10.23, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE64D', 'Hepatitis B Virus Profile (HBV Profile)', NULL, 23.07, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE105', 'Hepatitis C screening', NULL, 12.32, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 33, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE65D', 'High Vaginal Swab for C/S', NULL, 19.87, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE66D', 'High Vaginal Swab Routine Examination', NULL, 11.43, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE67D', 'Histopathology', NULL, 38.28, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE143', 'Holter', NULL, 104.90, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE68D', 'Human Immunodeficiency Virus (HIV) Confirmation', NULL, 19.71, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE69D', 'Human Immunodeficiency Virus (HIV) Screening', NULL, 17.86, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE70D', 'Hysterosalpingogram', NULL, 63.19, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE71D', 'Immunostaining', NULL, 71.30, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE72D', 'Intravenous Urography', NULL, 264.14, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE106', 'IOPA Xray', NULL, 18.48, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE124', 'Keratometry', NULL, 16.06, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE73D', 'LDL - Cholesterol', NULL, 13.15, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE74D', 'LFT', NULL, 30.72, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE75D', 'Lipid Profile', NULL, 29.15, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE76D', 'Lupus Erythematosus Cell (Le Cell)', NULL, 15.86, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE77D', 'Luteinizing Hormone (LH)', NULL, 26.21, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE107', 'Magnesium', NULL, 12.78, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE122', 'Malaria Card Test (Dipstik assay/rapid card)', NULL, 4.62, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 34, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE78D', 'Mammogram', NULL, 56.34, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE79D', 'Miscelllaneous Cultures (Fluids, Aspirates & Exudates)', NULL, 18.17, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE80D', 'MRI - 1 Region + Contrast', NULL, 369.99, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE81D', 'MRI - 1 Region + No Contrast', NULL, 170.39, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE161', 'MRI 2 region with + contrast', NULL, 511.93, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE160', 'MRI 2 region with no contrast', NULL, 402.15, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE82D', 'Myelogram - 1 Region', NULL, 114.88, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE145', 'Myocardial perfusion imaging', NULL, 201.86, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE108', 'NA+', NULL, 12.10, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE83D', 'Oral Glucose Tolerance Test (OGTT)', NULL, 24.24, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE84D', 'Orthopanthomograph (OPT)', NULL, 52.64, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE85D', 'Pancreatic Amylase', NULL, 17.07, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE86D', 'Pap Smear/Fine Needle Aspiration', NULL, 31.25, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE87D', 'Percutaneous Biopsy - CT Scan Guide', NULL, 120.86, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE88D', 'Percutaneous Biopsy - Flouroscopic Guide', NULL, 95.36, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE109', 'Phosphorus', NULL, 12.80, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 35, true, NOW());

COMMIT;
