-- Run after 00-setup-reset-and-versions.sql.
-- If this batch was already run and you need to restart, rerun 00 first.

BEGIN;

-- Tariff seed batch 13 of 14. Split so Supabase SQL Editor does not truncate one very large INSERT.
INSERT INTO public.nhia_tariff_items (
  tariff_version, facility_group, catering_option, mdc, gdrg_code, description,
  age_band, tariff_amount, currency, source_file, source_page, is_active, updated_at
)
VALUES
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE91D', 'Plasma Cortisol', NULL, 11.18, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE110', 'Platelet Count', NULL, 9.53, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 35, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE136', 'Pleural fluid analysis', NULL, 17.27, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE111', 'Potassium', NULL, 12.80, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE92D', 'Pregnancy Test', NULL, 10.49, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE93D', 'Progesterone (Prog)', NULL, 26.62, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE94D', 'Prostate Specific Antigen (PSA)', NULL, 28.18, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE95D', 'Prothrombin Time', NULL, 15.46, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE135', 'Pulmonary Function test', NULL, 49.71, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE112', 'Renal Function Test', NULL, 20.98, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE96D', 'Reticulocyte Count (Retics)', NULL, 9.61, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE123', 'RH Typing', NULL, 9.56, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE97D', 'Rheumatoid Factor', NULL, 8.19, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE98D', 'Routine Stool Examination', NULL, 7.83, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE99D', 'Routine Urine Examination', NULL, 8.45, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE113', 'Semen Analysis', NULL, 51.10, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE01E', 'Serum Adrenocorticotropic Hormone (ACTH)', NULL, 10.92, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE02E', 'Serum Albumin', NULL, 12.62, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE03E', 'Serum Alkalne Phosphatase (ALP)', NULL, 11.98, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE04E', 'Serum Beta-Human Chorionic Gonadotropin (HCG)', NULL, 25.23, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 36, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE05E', 'Serum Calcium', NULL, 15.86, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE06E', 'Serum Creatinine', NULL, 12.19, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE07E', 'Serum Electrolyte (Na+, K+)', NULL, 13.52, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE08E', 'Serum Ferritin', NULL, 23.15, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE09E', 'Serum Iron (Fe)', NULL, 13.29, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE10E', 'Serum Lactate Dehydrogenase (LDH)', NULL, 13.29, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE11E', 'Serum Prolactin (PRL)', NULL, 26.23, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE12E', 'Serum Total Protein', NULL, 11.37, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE13E', 'Serum Triglyceride', NULL, 12.29, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE14E', 'Serum Uric Acid', NULL, 14.32, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE126', 'Serum vitamin B12, and folate levels', NULL, 102.75, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE15E', 'Sialogram', NULL, 82.32, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE16E', 'Sickling Test', NULL, 8.16, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE17E', 'Skin Scrapping for Fungal Elements', NULL, 9.20, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE18E', 'Skin Snip', NULL, 9.22, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE19E', 'Stool C/S', NULL, 20.02, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE20E', 'Stool For Occult Blood', NULL, 9.32, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE21E', 'T3', NULL, 50.28, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 37, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE22E', 'T4', NULL, 50.28, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE23E', 'Testosterone', NULL, 31.71, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE24E', 'Thyroid Function Test (TSH)', NULL, 30.49, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE25E', 'Thyroid Profile', NULL, 67.59, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE26E', 'Total Iron Binding Capacity (TIBC)', NULL, 15.71, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE114', 'Total leucocyte count', NULL, 10.66, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE115', 'Total Proteins Blood', NULL, 9.69, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE27E', 'Total Serum Cholesterol', NULL, 11.75, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE138', 'Transhepatic cholangiography (PTC)', NULL, 113.66, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE28E', 'Trophozoite Count', NULL, 14.18, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE29E', 'Troponin', NULL, 23.35, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE149', 'Typhi Dot', NULL, 14.03, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE30E', 'Ultrasound', NULL, 38.57, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE31E', 'Ultrasound - 2 Regions', NULL, 53.97, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE129', 'Ultrasound biomicroscopy', NULL, 51.82, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE32E', 'Ultrasound Guided Incision & Drainage', NULL, 66.53, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE33E', 'Urethrogram', NULL, 78.67, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE34E', 'Urine C/S', NULL, 18.48, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 38, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE35E', 'Urine For Bence Jones Protein', NULL, 7.83, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 39, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE116', 'Urine Sugar', NULL, 7.49, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 39, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE117', 'VCT', NULL, 4.00, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 39, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE36E', 'Veneral Disease Research Laboratory (VDRL)', NULL, 8.27, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 39, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE37E', 'Venogram - 1 Region', NULL, 237.36, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 39, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE133', 'Viral serology', NULL, 105.21, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 39, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE118', 'Vitality Test', NULL, 24.82, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 39, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE119', 'VLDL', NULL, 9.83, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 39, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE120', 'WBC+Differential', NULL, 12.21, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 39, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE38E', 'Widal Test', NULL, 10.71, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 39, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE89D', 'X-ray one region', NULL, 34.80, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 39, true, NOW()),
  ('FEB 2023', 'Private Primary Care Hospital', 'inclusive', 'Investigation', 'INVE90D', 'X-ray two region', NULL, 53.62, 'GHS', 'Private Primary Care (Catering Inclusive).pdf', 39, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Obstetrics And Gynaecology', 'OBGY34A', 'Spontaneous Vaginal Delivery with or without Episiotomy', NULL, 65.34, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 3, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Zoom', 'ZOOM02A', 'Detention for Observation and Treatment - Adult', NULL, 16.12, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 3, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Zoom', 'ZOOM02C', 'Detention for Observation and Treatment - Child', NULL, 19.53, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 3, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Zoom', 'ZOOM04A', 'Change of Catheter >= 12 Yrs', '>= 12 Yrs', 16.06, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 3, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Zoom', 'ZOOM04C', 'Change of Catheter <12 Yrs', '<12 Yrs', 16.06, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 3, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Zoom', 'ZOOM05A', 'Change of Dressing >= 12 Yrs', '>= 12 Yrs', 17.61, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 3, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Zoom', 'ZOOM05C', 'Change of Dressing < 12 Yrs', '< 12 Yrs', 17.61, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 3, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Zoom', 'ZOOM06A', 'Male Circumcision >=12 Yrs', '>=12 Yrs', 49.59, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 3, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Zoom', 'ZOOM06C', 'Male Circumcision <12 Yrs', '<12 Yrs', 49.59, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 3, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Zoom', 'ZOOM07A', 'Dressing And Minor Suturing >=12 Yrs', '>=12 Yrs', 18.66, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 3, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Zoom', 'ZOOM07C', 'Dressing And Minor Suturing <=12 Yrs', '<=12 Yrs', 18.66, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 3, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Zoom', 'ZOOM10A', 'IUD >=12 Yrs', '>=12 Yrs', 11.00, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 3, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Zoom', 'ZOOM11A', 'Implant >=12 Yrs', '>=12 Yrs', 11.00, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 3, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Zoom', 'ZOOM12A', 'Injectable (Three Months) >=12 Yrs', '>=12 Yrs', 5.00, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 4, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Zoom', 'ZOOM13A', 'Injectable (One Month) >=12 Yrs', '>=12 Yrs', 1.67, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 4, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Out Patient', 'OPDC02A', 'Antenatal/Postnatal', NULL, 19.94, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 4, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Out Patient', 'OPDC06A', 'General OPD - Adult', NULL, 18.08, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 4, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Out Patient', 'OPDC06C', 'General OPD - Child', NULL, 18.08, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 4, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Out Patient', 'OPDC11A', 'Unbundled Consultation - Adult', NULL, 10.78, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 4, true, NOW()),
  ('FEB 2023', 'CHAG Health Centre and Clinic', NULL, 'Out Patient', 'OPDC11C', 'Unbundled Consultation - Child', NULL, 10.78, 'GHS', 'Tariff for CHAG Health Centre and Clinic.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT01A', 'Forceps Extraction of Tooth >=12 Yrs', '>=12 Yrs', 101.75, 'GHS', 'Tariff for Dental Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT01C', 'Forceps Extraction of Tooth <12 Yrs', '<12 Yrs', 98.83, 'GHS', 'Tariff for Dental Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT02A', 'Surgical Removal of Tooth >=12 Yrs', '>=12 Yrs', 140.00, 'GHS', 'Tariff for Dental Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT03A', 'Temporary Filling >=12 Yrs', '>=12 Yrs', 116.45, 'GHS', 'Tariff for Dental Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT03C', 'Temporary Filling <12 Yrs', '<12 Yrs', 117.16, 'GHS', 'Tariff for Dental Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT04A', 'Amalgam Filling >=12 Yrs', '>=12 Yrs', 121.21, 'GHS', 'Tariff for Dental Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT04C', 'Amalgam Filling <12 Yrs', '<12 Yrs', 138.54, 'GHS', 'Tariff for Dental Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT05A', 'Composite/GI Filling >=12 Yrs', '>=12 Yrs', 141.07, 'GHS', 'Tariff for Dental Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT05C', 'Composite/GI Filling <12 Yrs', '<12 Yrs', 125.61, 'GHS', 'Tariff for Dental Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT06A', 'Scaling & Polishing >=12 Yrs', '>=12 Yrs', 107.74, 'GHS', 'Tariff for Dental Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT06C', 'Scaling & Polishing <12 Yrs', '<12 Yrs', 92.36, 'GHS', 'Tariff for Dental Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT07A', 'Gingivectomy >=12 Yrs', '>=12 Yrs', 143.04, 'GHS', 'Tariff for Dental Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT07C', 'Gingivectomy <12 Yrs', '<12 Yrs', 143.42, 'GHS', 'Tariff for Dental Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT08A', 'Root Canal Therapy - Single Root (RCT) >=12 Yrs', '>=12 Yrs', 165.93, 'GHS', 'Tariff for Dental Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT08C', 'Root Canal Therapy - Single Root (RCT) <12 Yrs', '<12 Yrs', 162.57, 'GHS', 'Tariff for Dental Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT09A', 'Apicectomy >=12 Yrs', '>=12 Yrs', 255.12, 'GHS', 'Tariff for Dental Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT09C', 'Apicectomy <12 Yrs', '<12 Yrs', 223.47, 'GHS', 'Tariff for Dental Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT10A', 'Incision and Drainage (I & D) of Oro-Facial Abscess >=12 Yrs', '>=12 Yrs', 111.65, 'GHS', 'Tariff for Dental Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT10C', 'Incision and Drainage (I & D) of Oro-Facial Abscess <12 Yrs', '<12 Yrs', 105.20, 'GHS', 'Tariff for Dental Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT11A', 'Surgical Excision of Intraoral Lesions >=12 Yrs', '>=12 Yrs', 172.99, 'GHS', 'Tariff for Dental Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT11C', 'Surgical Excision of Intraoral Lesions <12 Yrs', '<12 Yrs', 156.89, 'GHS', 'Tariff for Dental Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT12A', 'Curetage/Sequestrectomy of Facial Bone >=12 Yrs', '>=12 Yrs', 259.45, 'GHS', 'Tariff for Dental Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT12C', 'Curetage/Sequestrectomy of Facial Bone <12 Yrs', '<12 Yrs', 237.27, 'GHS', 'Tariff for Dental Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT13A', 'Removal of Stone from Salivary Duct >=12 Yrs', '>=12 Yrs', 278.69, 'GHS', 'Tariff for Dental Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT13C', 'Removal of Stone from Salivary Duct <12 Yrs', '<12 Yrs', 232.09, 'GHS', 'Tariff for Dental Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT15A', 'Suturing of Lacerations of Facial Region >=12 Yrs', '>=12 Yrs', 159.99, 'GHS', 'Tariff for Dental Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT15C', 'Suturing of Lacerations of Facial Region <12 Yrs', '<12 Yrs', 135.30, 'GHS', 'Tariff for Dental Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT16A', 'Dressing of Open Facial Wounds >=12 Yrs', '>=12 Yrs', 128.18, 'GHS', 'Tariff for Dental Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT16C', 'Dressing of Open Facial Wounds <12 Yrs', '<12 Yrs', 117.87, 'GHS', 'Tariff for Dental Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT17A', 'Frenectomy/Frenotomy >=12 Yrs', '>=12 Yrs', 114.55, 'GHS', 'Tariff for Dental Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT17C', 'Frenectomy/Frenotomy <12 Yrs', '<12 Yrs', 108.13, 'GHS', 'Tariff for Dental Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT20A', 'Closed Reduction of Fractures of Facial Bones (IMF) >=12 Yrs', '>=12 Yrs', 259.76, 'GHS', 'Tariff for Dental Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT20C', 'Closed Reduction of Fractures of Facial Bones (IMF) <12 Yrs', '<12 Yrs', 235.16, 'GHS', 'Tariff for Dental Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT22A', 'Removal of Dental Wiring >=12 Yrs', '>=12 Yrs', 117.56, 'GHS', 'Tariff for Dental Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT22C', 'Removal of Dental Wiring <12 Yrs', '<12 Yrs', 75.46, 'GHS', 'Tariff for Dental Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT23A', 'Manual Reduction of TMJ Dislocation >=12 Yrs', '>=12 Yrs', 46.56, 'GHS', 'Tariff for Dental Centres.pdf', 5, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT23C', 'Manual Reduction of TMJ Dislocation <12 Yrs', '<12 Yrs', 44.56, 'GHS', 'Tariff for Dental Centres.pdf', 5, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT24A', 'Dental Examination (Medical Management) >=12 Yrs', '>=12 Yrs', 45.54, 'GHS', 'Tariff for Dental Centres.pdf', 5, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Dental', 'DENT24C', 'Dental Examination (Medical Management) <12 Yrs', '<12 Yrs', 44.09, 'GHS', 'Tariff for Dental Centres.pdf', 5, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Out Patient', 'OPDC03A', 'Dental Adult (without procedure)', NULL, 21.19, 'GHS', 'Tariff for Dental Centres.pdf', 5, true, NOW()),
  ('FEB 2023', 'Dental Centre', NULL, 'Out Patient', 'OPDC03C', 'Dental Child (without procedure)', NULL, 21.19, 'GHS', 'Tariff for Dental Centres.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE01D', '2 Hour Post Prandial Blood Glucose', NULL, 21.28, 'GHS', 'Tariff for Diagnostic Centre.pdf', 3, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE02D', '24hr Urine for Protein', NULL, 15.76, 'GHS', 'Tariff for Diagnostic Centre.pdf', 3, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE100', 'Acid Phosphate', NULL, 12.43, 'GHS', 'Tariff for Diagnostic Centre.pdf', 3, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE150', 'AEC', NULL, 15.27, 'GHS', 'Tariff for Diagnostic Centre.pdf', 3, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE03D', 'Alanine Aminotransferase (ALT)', NULL, 15.89, 'GHS', 'Tariff for Diagnostic Centre.pdf', 3, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE04D', 'Alpha Amylase (Serum/Urine)', NULL, 21.08, 'GHS', 'Tariff for Diagnostic Centre.pdf', 3, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE05D', 'Alpha-Fetoprotein (AFP)', NULL, 14.81, 'GHS', 'Tariff for Diagnostic Centre.pdf', 3, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE132', 'Anti-streptolysin test', NULL, 23.76, 'GHS', 'Tariff for Diagnostic Centre.pdf', 3, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE06D', 'Ap-Prothrombin Time', NULL, 17.87, 'GHS', 'Tariff for Diagnostic Centre.pdf', 3, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE07D', 'Arterial Blood Gas (ABG)', NULL, 25.43, 'GHS', 'Tariff for Diagnostic Centre.pdf', 3, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE125', 'A-scan', NULL, 53.20, 'GHS', 'Tariff for Diagnostic Centre.pdf', 3, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE154', 'ASO titre', NULL, 31.62, 'GHS', 'Tariff for Diagnostic Centre.pdf', 3, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE08D', 'Aspartate Aminotransferase (AST)', NULL, 13.89, 'GHS', 'Tariff for Diagnostic Centre.pdf', 3, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE09D', 'B/F for Malaria Parasites', NULL, 9.77, 'GHS', 'Tariff for Diagnostic Centre.pdf', 3, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE10D', 'Barium Enema', NULL, 185.13, 'GHS', 'Tariff for Diagnostic Centre.pdf', 3, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE11D', 'Barium Meal', NULL, 117.32, 'GHS', 'Tariff for Diagnostic Centre.pdf', 3, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE12D', 'Barium Meal & Follow Through', NULL, 126.66, 'GHS', 'Tariff for Diagnostic Centre.pdf', 3, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE13D', 'Barium Swallow', NULL, 107.52, 'GHS', 'Tariff for Diagnostic Centre.pdf', 4, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE14D', 'Bilirubin', NULL, 13.89, 'GHS', 'Tariff for Diagnostic Centre.pdf', 4, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE152', 'Biopsy L/A', NULL, 104.57, 'GHS', 'Tariff for Diagnostic Centre.pdf', 4, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE15D', 'Bleeding and Clotting Time', NULL, 10.92, 'GHS', 'Tariff for Diagnostic Centre.pdf', 4, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE16D', 'Blood for C/S', NULL, 22.25, 'GHS', 'Tariff for Diagnostic Centre.pdf', 4, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE17D', 'Blood Grouping', NULL, 11.71, 'GHS', 'Tariff for Diagnostic Centre.pdf', 4, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE18D', 'Blood Grouping & Antibody Screen', NULL, 14.99, 'GHS', 'Tariff for Diagnostic Centre.pdf', 4, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE19D', 'Blood Parasites', NULL, 14.76, 'GHS', 'Tariff for Diagnostic Centre.pdf', 4, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE151', 'Blood Sugar PP', NULL, 8.42, 'GHS', 'Tariff for Diagnostic Centre.pdf', 4, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE20D', 'Blood Urea', NULL, 22.08, 'GHS', 'Tariff for Diagnostic Centre.pdf', 4, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE21D', 'Blood Urea & Electrolytes', NULL, 24.36, 'GHS', 'Tariff for Diagnostic Centre.pdf', 4, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE22D', 'Bone Marrow - Trephine Biopsy', NULL, 133.14, 'GHS', 'Tariff for Diagnostic Centre.pdf', 4, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE23D', 'Bone Marrow Aspirate', NULL, 87.96, 'GHS', 'Tariff for Diagnostic Centre.pdf', 4, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE139', 'Bone Scan', NULL, 122.55, 'GHS', 'Tariff for Diagnostic Centre.pdf', 4, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE140', 'Breast tissue Biopsy', NULL, 34.08, 'GHS', 'Tariff for Diagnostic Centre.pdf', 4, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE24D', 'Bue & Creatinine', NULL, 25.60, 'GHS', 'Tariff for Diagnostic Centre.pdf', 4, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE141', 'C Reactive Protein', NULL, 22.29, 'GHS', 'Tariff for Diagnostic Centre.pdf', 4, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE134', 'Calcium Infusion test', NULL, 25.60, 'GHS', 'Tariff for Diagnostic Centre.pdf', 4, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE137', 'Cancer antigen 19-9', NULL, 93.43, 'GHS', 'Tariff for Diagnostic Centre.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE25D', 'Carcino Embryonic Antigen (CEA)', NULL, 13.42, 'GHS', 'Tariff for Diagnostic Centre.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE26D', 'Cerebrospinal Fluid for C/S', NULL, 24.13, 'GHS', 'Tariff for Diagnostic Centre.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE101', 'Chloride', NULL, 12.72, 'GHS', 'Tariff for Diagnostic Centre.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE27D', 'Clusters Of Differentiation Cells (CD4)', NULL, 76.98, 'GHS', 'Tariff for Diagnostic Centre.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE28D', 'Coombs Test (Direct)', NULL, 15.14, 'GHS', 'Tariff for Diagnostic Centre.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE29D', 'Creatine Kinase - Mb (CK - Mb)', NULL, 20.58, 'GHS', 'Tariff for Diagnostic Centre.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE30D', 'Creatine Kinase (CK)', NULL, 17.23, 'GHS', 'Tariff for Diagnostic Centre.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE31D', 'CSF Latex Agglutination', NULL, 16.06, 'GHS', 'Tariff for Diagnostic Centre.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE33D', 'CT Scan - 1 Region + 1IV Contrast', NULL, 308.96, 'GHS', 'Tariff for Diagnostic Centre.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE32D', 'CT Scan - 1 Region + 2 Contrast', NULL, 384.95, 'GHS', 'Tariff for Diagnostic Centre.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE34D', 'CT Scan - 1 Region + No Contrast', NULL, 110.82, 'GHS', 'Tariff for Diagnostic Centre.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE158', 'CT Scan - 2 Region + 1Contrast', NULL, 196.86, 'GHS', 'Tariff for Diagnostic Centre.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE159', 'CT Scan - 2 region + 2 contrast', NULL, 221.60, 'GHS', 'Tariff for Diagnostic Centre.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE157', 'CT Scan - 2 Region with No Contrast', NULL, 192.45, 'GHS', 'Tariff for Diagnostic Centre.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE35D', 'Cystogram', NULL, 108.28, 'GHS', 'Tariff for Diagnostic Centre.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE36D', 'Cytology', NULL, 24.58, 'GHS', 'Tariff for Diagnostic Centre.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE130', 'Demonstration of Heinz bodies', NULL, 14.29, 'GHS', 'Tariff for Diagnostic Centre.pdf', 5, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE37D', 'Digoxin Level', NULL, 11.86, 'GHS', 'Tariff for Diagnostic Centre.pdf', 6, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE38D', 'Dihydroxy Epiandesterone Sulphate (Dhea-S)', NULL, 12.77, 'GHS', 'Tariff for Diagnostic Centre.pdf', 6, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE102', 'Direct Bilirubin/Total Bilirubin', NULL, 15.94, 'GHS', 'Tariff for Diagnostic Centre.pdf', 6, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE103', 'Donor Screening For HB & AG', NULL, 23.23, 'GHS', 'Tariff for Diagnostic Centre.pdf', 6, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE39D', 'Doppler Scan', NULL, 41.21, 'GHS', 'Tariff for Diagnostic Centre.pdf', 6, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE40D', 'Ductologram/Galactographyy', NULL, 84.66, 'GHS', 'Tariff for Diagnostic Centre.pdf', 6, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE41D', 'ECG', NULL, 17.71, 'GHS', 'Tariff for Diagnostic Centre.pdf', 6, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE142', 'EEG (Electroencephalogram)', NULL, 68.41, 'GHS', 'Tariff for Diagnostic Centre.pdf', 6, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE42D', 'Erythrocyte Sedimentation Rate (ESR)', NULL, 8.87, 'GHS', 'Tariff for Diagnostic Centre.pdf', 6, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE43D', 'Estrogen', NULL, 26.77, 'GHS', 'Tariff for Diagnostic Centre.pdf', 6, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE44D', 'Factor IX', NULL, 33.13, 'GHS', 'Tariff for Diagnostic Centre.pdf', 6, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE45D', 'Factor VIII', NULL, 72.45, 'GHS', 'Tariff for Diagnostic Centre.pdf', 6, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE46D', 'Fasting Blood Sugar/Random Blood Sugar', NULL, 10.01, 'GHS', 'Tariff for Diagnostic Centre.pdf', 6, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE47D', 'Fistulogram', NULL, 149.96, 'GHS', 'Tariff for Diagnostic Centre.pdf', 6, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE48D', 'Follicle Stimulating Hormone (FSH)', NULL, 28.78, 'GHS', 'Tariff for Diagnostic Centre.pdf', 6, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE49D', 'FT3', NULL, 33.04, 'GHS', 'Tariff for Diagnostic Centre.pdf', 6, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE50D', 'FT4', NULL, 33.04, 'GHS', 'Tariff for Diagnostic Centre.pdf', 6, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE51D', 'Full Blood Count FBC (Auto) & Film Comment', NULL, 24.26, 'GHS', 'Tariff for Diagnostic Centre.pdf', 6, true, NOW());

COMMIT;
