-- Run after 00-setup-reset-and-versions.sql.
-- If this batch was already run and you need to restart, rerun 00 first.

BEGIN;

-- Tariff seed batch 14 of 14. Split so Supabase SQL Editor does not truncate one very large INSERT.
INSERT INTO public.nhia_tariff_items (
  tariff_version, facility_group, catering_option, mdc, gdrg_code, description,
  age_band, tariff_amount, currency, source_file, source_page, is_active, updated_at
)
VALUES
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE52D', 'Full Blood Count FBC (Automation)', NULL, 20.80, 'GHS', 'Tariff for Diagnostic Centre.pdf', 7, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE53D', 'Full Blood Count with Film Comment (Manual)', NULL, 23.51, 'GHS', 'Tariff for Diagnostic Centre.pdf', 7, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE54D', 'Fungal Cultures', NULL, 23.93, 'GHS', 'Tariff for Diagnostic Centre.pdf', 7, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE55D', 'Gamma Glutamyl Transferase (GGT)', NULL, 20.58, 'GHS', 'Tariff for Diagnostic Centre.pdf', 7, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE56D', 'Glucose-6-Phosphate Dehydrogenase (G6PD)', NULL, 13.89, 'GHS', 'Tariff for Diagnostic Centre.pdf', 7, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE57D', 'Glycosylated Haemoglobin (HBA 1C)', NULL, 28.11, 'GHS', 'Tariff for Diagnostic Centre.pdf', 7, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE155', 'Gonioscopy', NULL, 14.05, 'GHS', 'Tariff for Diagnostic Centre.pdf', 7, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE104', 'Grouping/X'' Matching/Unit', NULL, 13.64, 'GHS', 'Tariff for Diagnostic Centre.pdf', 7, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE146', 'Guthrie test', NULL, 67.96, 'GHS', 'Tariff for Diagnostic Centre.pdf', 7, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE58D', 'Haemoglobin A2 & F Estimation', NULL, 13.85, 'GHS', 'Tariff for Diagnostic Centre.pdf', 7, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE59D', 'Haemoglobin Electrophoresis', NULL, 16.46, 'GHS', 'Tariff for Diagnostic Centre.pdf', 7, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE60D', 'Haemoglobin Estimation (HB)', NULL, 10.15, 'GHS', 'Tariff for Diagnostic Centre.pdf', 7, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE61D', 'HDL - Cholesterol', NULL, 15.89, 'GHS', 'Tariff for Diagnostic Centre.pdf', 7, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE62D', 'Helicobacter Pylori Test', NULL, 10.74, 'GHS', 'Tariff for Diagnostic Centre.pdf', 7, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE156', 'Hematocrit', NULL, 20.22, 'GHS', 'Tariff for Diagnostic Centre.pdf', 7, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE63D', 'Hepatitis B Surface Antigen (HBSAG) HBV', NULL, 11.12, 'GHS', 'Tariff for Diagnostic Centre.pdf', 7, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE64D', 'Hepatitis B Virus Profile (HBV Profile)', NULL, 25.06, 'GHS', 'Tariff for Diagnostic Centre.pdf', 7, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE105', 'Hepatitis C screening', NULL, 13.38, 'GHS', 'Tariff for Diagnostic Centre.pdf', 7, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE65D', 'High Vaginal Swab for C/S', NULL, 21.58, 'GHS', 'Tariff for Diagnostic Centre.pdf', 8, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE66D', 'High Vaginal Swab Routine Examination', NULL, 12.41, 'GHS', 'Tariff for Diagnostic Centre.pdf', 8, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE67D', 'Histopathology', NULL, 41.59, 'GHS', 'Tariff for Diagnostic Centre.pdf', 8, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE143', 'Holter', NULL, 113.97, 'GHS', 'Tariff for Diagnostic Centre.pdf', 8, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE68D', 'Human Immunodeficiency Virus (HIV) Confirmation', NULL, 21.42, 'GHS', 'Tariff for Diagnostic Centre.pdf', 8, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE69D', 'Human Immunodeficiency Virus (HIV) Screening', NULL, 19.41, 'GHS', 'Tariff for Diagnostic Centre.pdf', 8, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE70D', 'Hysterosalpingogram', NULL, 68.66, 'GHS', 'Tariff for Diagnostic Centre.pdf', 8, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE71D', 'Immunostaining', NULL, 77.46, 'GHS', 'Tariff for Diagnostic Centre.pdf', 8, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE72D', 'Intravenous Urography', NULL, 286.97, 'GHS', 'Tariff for Diagnostic Centre.pdf', 8, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE106', 'IOPA Xray', NULL, 20.08, 'GHS', 'Tariff for Diagnostic Centre.pdf', 8, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE124', 'Keratometry', NULL, 17.45, 'GHS', 'Tariff for Diagnostic Centre.pdf', 8, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE73D', 'LDL - Cholesterol', NULL, 14.29, 'GHS', 'Tariff for Diagnostic Centre.pdf', 8, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE74D', 'LFT', NULL, 33.37, 'GHS', 'Tariff for Diagnostic Centre.pdf', 8, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE75D', 'Lipid Profile', NULL, 31.67, 'GHS', 'Tariff for Diagnostic Centre.pdf', 8, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE76D', 'Lupus Erythematosus Cell (Le Cell)', NULL, 17.23, 'GHS', 'Tariff for Diagnostic Centre.pdf', 8, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE77D', 'Luteinizing Hormone (LH)', NULL, 28.48, 'GHS', 'Tariff for Diagnostic Centre.pdf', 8, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE107', 'Magnesium', NULL, 13.89, 'GHS', 'Tariff for Diagnostic Centre.pdf', 8, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE122', 'Malaria Card Test (Dipstik assay/rapid card)', NULL, 5.02, 'GHS', 'Tariff for Diagnostic Centre.pdf', 8, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE78D', 'Mammogram', NULL, 61.21, 'GHS', 'Tariff for Diagnostic Centre.pdf', 9, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE79D', 'Miscelllaneous Cultures (Fluids, Aspirates & Exudates)', NULL, 19.74, 'GHS', 'Tariff for Diagnostic Centre.pdf', 9, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE80D', 'MRI - 1 Region + Contrast', NULL, 401.96, 'GHS', 'Tariff for Diagnostic Centre.pdf', 9, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE81D', 'MRI - 1 Region + No Contrast', NULL, 185.11, 'GHS', 'Tariff for Diagnostic Centre.pdf', 9, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE161', 'MRI 2 region with + contrast', NULL, 556.18, 'GHS', 'Tariff for Diagnostic Centre.pdf', 9, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE160', 'MRI 2 region with no contrast', NULL, 436.91, 'GHS', 'Tariff for Diagnostic Centre.pdf', 9, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE82D', 'Myelogram - 1 Region', NULL, 124.81, 'GHS', 'Tariff for Diagnostic Centre.pdf', 9, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE145', 'Myocardial perfusion imaging', NULL, 219.31, 'GHS', 'Tariff for Diagnostic Centre.pdf', 9, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE108', 'NA+', NULL, 13.15, 'GHS', 'Tariff for Diagnostic Centre.pdf', 9, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE83D', 'Oral Glucose Tolerance Test (OGTT)', NULL, 26.33, 'GHS', 'Tariff for Diagnostic Centre.pdf', 9, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE84D', 'Orthopanthomograph (OPT)', NULL, 57.19, 'GHS', 'Tariff for Diagnostic Centre.pdf', 9, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE85D', 'Pancreatic Amylase', NULL, 18.54, 'GHS', 'Tariff for Diagnostic Centre.pdf', 9, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE86D', 'Pap Smear/Fine Needle Aspiration', NULL, 33.95, 'GHS', 'Tariff for Diagnostic Centre.pdf', 9, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE87D', 'Percutaneous Biopsy - CT Scan Guide', NULL, 131.31, 'GHS', 'Tariff for Diagnostic Centre.pdf', 9, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE88D', 'Percutaneous Biopsy - Flouroscopic Guide', NULL, 103.60, 'GHS', 'Tariff for Diagnostic Centre.pdf', 9, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE109', 'Phosphorus', NULL, 13.91, 'GHS', 'Tariff for Diagnostic Centre.pdf', 9, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE91D', 'Plasma Cortisol', NULL, 12.15, 'GHS', 'Tariff for Diagnostic Centre.pdf', 9, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE110', 'Platelet Count', NULL, 10.36, 'GHS', 'Tariff for Diagnostic Centre.pdf', 9, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE136', 'Pleural fluid analysis', NULL, 18.77, 'GHS', 'Tariff for Diagnostic Centre.pdf', 10, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE111', 'Potassium', NULL, 13.91, 'GHS', 'Tariff for Diagnostic Centre.pdf', 10, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE92D', 'Pregnancy Test', NULL, 11.40, 'GHS', 'Tariff for Diagnostic Centre.pdf', 10, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE93D', 'Progesterone (Prog)', NULL, 28.92, 'GHS', 'Tariff for Diagnostic Centre.pdf', 10, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE94D', 'Prostate Specific Antigen (PSA)', NULL, 30.62, 'GHS', 'Tariff for Diagnostic Centre.pdf', 10, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE95D', 'Prothrombin Time', NULL, 16.80, 'GHS', 'Tariff for Diagnostic Centre.pdf', 10, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE135', 'Pulmonary Function test', NULL, 54.01, 'GHS', 'Tariff for Diagnostic Centre.pdf', 10, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE112', 'Renal Function Test', NULL, 22.79, 'GHS', 'Tariff for Diagnostic Centre.pdf', 10, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE96D', 'Reticulocyte Count (Retics)', NULL, 10.44, 'GHS', 'Tariff for Diagnostic Centre.pdf', 10, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE123', 'RH Typing', NULL, 10.39, 'GHS', 'Tariff for Diagnostic Centre.pdf', 10, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE97D', 'Rheumatoid Factor', NULL, 8.90, 'GHS', 'Tariff for Diagnostic Centre.pdf', 10, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE98D', 'Routine Stool Examination', NULL, 8.51, 'GHS', 'Tariff for Diagnostic Centre.pdf', 10, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE99D', 'Routine Urine Examination', NULL, 9.18, 'GHS', 'Tariff for Diagnostic Centre.pdf', 10, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE113', 'Semen Analysis', NULL, 55.52, 'GHS', 'Tariff for Diagnostic Centre.pdf', 10, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE01E', 'Serum Adrenocorticotropic Hormone (ACTH)', NULL, 11.87, 'GHS', 'Tariff for Diagnostic Centre.pdf', 10, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE02E', 'Serum Albumin', NULL, 13.71, 'GHS', 'Tariff for Diagnostic Centre.pdf', 10, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE03E', 'Serum Alkalne Phosphatase (ALP)', NULL, 13.02, 'GHS', 'Tariff for Diagnostic Centre.pdf', 10, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE04E', 'Serum Beta-Human Chorionic Gonadotropin (HCG)', NULL, 27.41, 'GHS', 'Tariff for Diagnostic Centre.pdf', 10, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE05E', 'Serum Calcium', NULL, 17.23, 'GHS', 'Tariff for Diagnostic Centre.pdf', 11, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE06E', 'Serum Creatinine', NULL, 13.24, 'GHS', 'Tariff for Diagnostic Centre.pdf', 11, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE07E', 'Serum Electrolyte (Na+, K+)', NULL, 14.69, 'GHS', 'Tariff for Diagnostic Centre.pdf', 11, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE08E', 'Serum Ferritin', NULL, 25.16, 'GHS', 'Tariff for Diagnostic Centre.pdf', 11, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE09E', 'Serum Iron (Fe)', NULL, 14.44, 'GHS', 'Tariff for Diagnostic Centre.pdf', 11, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE10E', 'Serum Lactate Dehydrogenase (LDH)', NULL, 14.44, 'GHS', 'Tariff for Diagnostic Centre.pdf', 11, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE11E', 'Serum Prolactin (PRL)', NULL, 28.49, 'GHS', 'Tariff for Diagnostic Centre.pdf', 11, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE12E', 'Serum Total Protein', NULL, 12.35, 'GHS', 'Tariff for Diagnostic Centre.pdf', 11, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE13E', 'Serum Triglyceride', NULL, 13.35, 'GHS', 'Tariff for Diagnostic Centre.pdf', 11, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE14E', 'Serum Uric Acid', NULL, 15.56, 'GHS', 'Tariff for Diagnostic Centre.pdf', 11, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE126', 'Serum vitamin B12, and folate levels', NULL, 111.63, 'GHS', 'Tariff for Diagnostic Centre.pdf', 11, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE15E', 'Sialogram', NULL, 89.44, 'GHS', 'Tariff for Diagnostic Centre.pdf', 11, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE16E', 'Sickling Test', NULL, 8.87, 'GHS', 'Tariff for Diagnostic Centre.pdf', 11, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE17E', 'Skin Scrapping for Fungal Elements', NULL, 9.99, 'GHS', 'Tariff for Diagnostic Centre.pdf', 11, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE18E', 'Skin Snip', NULL, 10.02, 'GHS', 'Tariff for Diagnostic Centre.pdf', 11, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE19E', 'Stool C/S', NULL, 21.75, 'GHS', 'Tariff for Diagnostic Centre.pdf', 11, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE20E', 'Stool for Occult Blood', NULL, 10.13, 'GHS', 'Tariff for Diagnostic Centre.pdf', 11, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE21E', 'T3', NULL, 54.62, 'GHS', 'Tariff for Diagnostic Centre.pdf', 11, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE22E', 'T4', NULL, 54.62, 'GHS', 'Tariff for Diagnostic Centre.pdf', 12, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE23E', 'Testosterone', NULL, 34.45, 'GHS', 'Tariff for Diagnostic Centre.pdf', 12, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE24E', 'Thyroid Function Test (TSH)', NULL, 33.13, 'GHS', 'Tariff for Diagnostic Centre.pdf', 12, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE25E', 'Thyroid Profile', NULL, 73.43, 'GHS', 'Tariff for Diagnostic Centre.pdf', 12, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE26E', 'Total Iron Binding Capacity (TIBC)', NULL, 17.07, 'GHS', 'Tariff for Diagnostic Centre.pdf', 12, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE114', 'Total leucocyte count', NULL, 11.58, 'GHS', 'Tariff for Diagnostic Centre.pdf', 12, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE115', 'Total Proteins Blood', NULL, 10.53, 'GHS', 'Tariff for Diagnostic Centre.pdf', 12, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE27E', 'Total Serum Cholesterol', NULL, 12.77, 'GHS', 'Tariff for Diagnostic Centre.pdf', 12, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE138', 'Transhepatic cholangiography (PTC)', NULL, 123.48, 'GHS', 'Tariff for Diagnostic Centre.pdf', 12, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE28E', 'Trophozoite Count', NULL, 15.41, 'GHS', 'Tariff for Diagnostic Centre.pdf', 12, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE29E', 'Troponin', NULL, 25.37, 'GHS', 'Tariff for Diagnostic Centre.pdf', 12, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE149', 'Typhi Dot', NULL, 15.24, 'GHS', 'Tariff for Diagnostic Centre.pdf', 12, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE30E', 'Ultrasound', NULL, 41.90, 'GHS', 'Tariff for Diagnostic Centre.pdf', 12, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE31E', 'Ultrasound - 2 Regions', NULL, 58.63, 'GHS', 'Tariff for Diagnostic Centre.pdf', 12, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE129', 'Ultrasound biomicroscopy', NULL, 56.30, 'GHS', 'Tariff for Diagnostic Centre.pdf', 12, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE32E', 'Ultrasound Guided Incision & Drainage', NULL, 72.28, 'GHS', 'Tariff for Diagnostic Centre.pdf', 12, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE33E', 'Urethrogram', NULL, 85.47, 'GHS', 'Tariff for Diagnostic Centre.pdf', 12, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE34E', 'Urine C/S', NULL, 20.08, 'GHS', 'Tariff for Diagnostic Centre.pdf', 12, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE35E', 'Urine For Bence Jones Protein', NULL, 8.50, 'GHS', 'Tariff for Diagnostic Centre.pdf', 13, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE116', 'Urine Sugar', NULL, 8.14, 'GHS', 'Tariff for Diagnostic Centre.pdf', 13, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE117', 'VCT', NULL, 4.35, 'GHS', 'Tariff for Diagnostic Centre.pdf', 13, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE36E', 'Veneral Disease Research Laboratory (VDRL)', NULL, 8.98, 'GHS', 'Tariff for Diagnostic Centre.pdf', 13, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE37E', 'Venogram - 1 Region', NULL, 257.88, 'GHS', 'Tariff for Diagnostic Centre.pdf', 13, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE133', 'Viral serology', NULL, 114.31, 'GHS', 'Tariff for Diagnostic Centre.pdf', 13, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE118', 'Vitality Test', NULL, 26.97, 'GHS', 'Tariff for Diagnostic Centre.pdf', 13, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE119', 'VLDL', NULL, 10.67, 'GHS', 'Tariff for Diagnostic Centre.pdf', 13, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE120', 'WBC+Differential', NULL, 13.26, 'GHS', 'Tariff for Diagnostic Centre.pdf', 13, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE38E', 'Widal Test', NULL, 11.64, 'GHS', 'Tariff for Diagnostic Centre.pdf', 13, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE89D', 'X-ray one region', NULL, 37.81, 'GHS', 'Tariff for Diagnostic Centre.pdf', 13, true, NOW()),
  ('FEB 2023', 'Diagnostic Centre', NULL, 'Investigation', 'INVE90D', 'X-ray two region', NULL, 58.26, 'GHS', 'Tariff for Diagnostic Centre.pdf', 13, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT03A', 'Removal of superficial foreign body >=12 Yrs', '>=12 Yrs', 32.84, 'GHS', 'Tariff for Eye Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT03C', 'Removal of superficial foreign body <12 Yrs', '<12 Yrs', 28.42, 'GHS', 'Tariff for Eye Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT05A', 'Removal of intraorbital foreign body >=12 Yrs', '>=12 Yrs', 387.50, 'GHS', 'Tariff for Eye Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT05C', 'Removal of intraorbital foreign body <12 Yrs', '<12 Yrs', 344.96, 'GHS', 'Tariff for Eye Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT06A', 'Eyelid surgery >=12 Yrs', '>=12 Yrs', 216.83, 'GHS', 'Tariff for Eye Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT06C', 'Eyelid surgery <12 Yrs', '<12 Yrs', 225.04, 'GHS', 'Tariff for Eye Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT07A', 'Scleral and Corneal surgery >=12 Yrs', '>=12 Yrs', 206.81, 'GHS', 'Tariff for Eye Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT07C', 'Scleral and Corneal surgery <12 Yrs', '<12 Yrs', 262.75, 'GHS', 'Tariff for Eye Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT08A', 'Anterior chamber washout >=12 Yrs', '>=12 Yrs', 242.13, 'GHS', 'Tariff for Eye Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT08C', 'Anterior chamber washout <12 Yrs', '<12 Yrs', 189.80, 'GHS', 'Tariff for Eye Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT09A', 'Glaucoma surgery >=12 Yrs', '>=12 Yrs', 242.00, 'GHS', 'Tariff for Eye Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT09C', 'Glaucoma surgery <12 Yrs', '<12 Yrs', 234.38, 'GHS', 'Tariff for Eye Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT10A', 'Cataract surgery >=12 Yrs', '>=12 Yrs', 274.78, 'GHS', 'Tariff for Eye Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT10C', 'Cataract surgery <12 Yrs', '<12 Yrs', 276.06, 'GHS', 'Tariff for Eye Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT12A', 'Incision and curettage of eyelid >=12 Yrs', '>=12 Yrs', 197.75, 'GHS', 'Tariff for Eye Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT12C', 'Incision and curettage of eyelid <12 Yrs', '<12 Yrs', 211.92, 'GHS', 'Tariff for Eye Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT13A', 'Reconstructive surgery of eyelid >=12 Yrs', '>=12 Yrs', 196.14, 'GHS', 'Tariff for Eye Centres.pdf', 3, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT13C', 'Reconstructive surgery of eyelid <12 Yrs', '<12 Yrs', 216.06, 'GHS', 'Tariff for Eye Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT14A', 'Nasolacrimal drainage system surgery >=12 Yrs', '>=12 Yrs', 251.80, 'GHS', 'Tariff for Eye Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT14C', 'Nasolacrimal drainage system surgery <12 Yrs', '<12 Yrs', 216.92, 'GHS', 'Tariff for Eye Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT15A', 'Incision and drainage of abscesses >=12 Yrs', '>=12 Yrs', 238.00, 'GHS', 'Tariff for Eye Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT15C', 'Incision and drainage of abscesses <12 Yrs', '<12 Yrs', 230.88, 'GHS', 'Tariff for Eye Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT16A', 'Examination under anaesthesia >=12 Yrs', '>=12 Yrs', 54.29, 'GHS', 'Tariff for Eye Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT16C', 'Examination under anaesthesia <12 Yrs', '<12 Yrs', 53.08, 'GHS', 'Tariff for Eye Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT17A', 'Uveitis Management', NULL, 44.27, 'GHS', 'Tariff for Eye Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Opthalmology', 'OPHT18A', 'Cataract Surgery with Implants >=12 Yrs', '>=12 Yrs', 313.74, 'GHS', 'Tariff for Eye Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Out Patient', 'OPDC05A', 'Eye Adult (without procedure)', NULL, 21.18, 'GHS', 'Tariff for Eye Centres.pdf', 4, true, NOW()),
  ('FEB 2023', 'Eye Centre', NULL, 'Out Patient', 'OPDC05C', 'Eye Child (without procedure)', NULL, 21.18, 'GHS', 'Tariff for Eye Centres.pdf', 4, true, NOW());

COMMIT;
