import { afterEach, describe, expect, it, vi } from 'vitest'
import { startFacilityContactReporting } from './facilityConnectivityService'
vi.mock('../lib/supabase', () => ({ supabase: { rpc: vi.fn() } }))
afterEach(() => { vi.useRealTimers(); vi.restoreAllMocks() })
describe('facility contact reporting', () => {
  it('reports once per minute and cleans up without affecting auth', async () => {
    vi.useFakeTimers()
    const send = vi.fn().mockResolvedValue()
    const stop = startFacilityContactReporting({ send })
    await vi.advanceTimersByTimeAsync(0)
    expect(send).toHaveBeenCalledTimes(1)
    window.dispatchEvent(new Event('online'))
    document.dispatchEvent(new Event('visibilitychange'))
    expect(send).toHaveBeenCalledTimes(1)
    await vi.advanceTimersByTimeAsync(60000)
    expect(send).toHaveBeenCalledTimes(2)
    stop()
    await vi.advanceTimersByTimeAsync(120000)
    expect(send).toHaveBeenCalledTimes(2)
  })
  it('does not queue contact while offline or hidden and tolerates errors', async () => {
    vi.useFakeTimers()
    const online = vi.spyOn(navigator, 'onLine', 'get').mockReturnValue(false)
    const visible = vi.spyOn(document, 'visibilityState', 'get').mockReturnValue('hidden')
    const send = vi.fn().mockRejectedValue(new Error('offline'))
    const stop = startFacilityContactReporting({ send })
    await vi.advanceTimersByTimeAsync(60000)
    expect(send).not.toHaveBeenCalled()
    online.mockReturnValue(true)
    visible.mockReturnValue('visible')
    document.dispatchEvent(new Event('visibilitychange'))
    await vi.advanceTimersByTimeAsync(0)
    expect(send).toHaveBeenCalledOnce()
    stop()
  })
})
