import { afterEach, describe, expect, it, vi } from 'vitest'
import { startFacilityContactReporting, recordFacilityBrowserContact } from './facilityConnectivityService'
import { supabase, getCachedSupabaseSession } from '../lib/supabase'
vi.mock('../lib/supabase', () => ({ supabase: { rpc: vi.fn() }, getCachedSupabaseSession: vi.fn() }))
afterEach(() => { vi.useRealTimers(); vi.restoreAllMocks() })
describe('facility contact reporting', () => {
  it.each([null, {}, {access_token:'old',expires_at:1}, {access_token:'unknown'}])('skips contact without a usable session: %s', async (session) => {
    supabase.rpc.mockClear()
    getCachedSupabaseSession.mockReturnValue(session)
    await recordFacilityBrowserContact()
    expect(supabase.rpc).not.toHaveBeenCalled()
  })
  it('reports with a current session', async () => {
    supabase.rpc.mockClear()
    getCachedSupabaseSession.mockReturnValue({access_token:'current',expires_at:Date.now()/1000+3600})
    supabase.rpc.mockResolvedValue({error:null})
    await recordFacilityBrowserContact()
    expect(supabase.rpc).toHaveBeenCalledWith('record_facility_browser_contact')
  })
  it('reports once per minute and cleans up without affecting auth', async () => {
    vi.useFakeTimers()
    const send = vi.fn().mockResolvedValue()
    const stop = startFacilityContactReporting({ send })
    await vi.advanceTimersByTimeAsync(0)
    expect(send).toHaveBeenCalledTimes(1)
    window.dispatchEvent(new Event('online'))
    document.dispatchEvent(new Event('visibilitychange'))
    expect(send).toHaveBeenCalledTimes(1)
    await vi.advanceTimersByTimeAsync(60000)
    expect(send).toHaveBeenCalledTimes(2)
    stop()
    await vi.advanceTimersByTimeAsync(120000)
    expect(send).toHaveBeenCalledTimes(2)
  })
  it('does not queue contact while offline or hidden and tolerates errors', async () => {
    vi.useFakeTimers()
    const online = vi.spyOn(navigator, 'onLine', 'get').mockReturnValue(false)
    const visible = vi.spyOn(document, 'visibilityState', 'get').mockReturnValue('hidden')
    const send = vi.fn().mockRejectedValue(new Error('offline'))
    const stop = startFacilityContactReporting({ send })
    await vi.advanceTimersByTimeAsync(60000)
    expect(send).not.toHaveBeenCalled()
    online.mockReturnValue(true)
    visible.mockReturnValue('visible')
    document.dispatchEvent(new Event('visibilitychange'))
    await vi.advanceTimersByTimeAsync(0)
    expect(send).toHaveBeenCalledOnce()
    stop()
  })
})
