import { beforeEach, describe, expect, it, vi } from 'vitest'

const mocks = vi.hoisted(() => ({
  invokeSupabaseFunction: vi.fn(),
}))

vi.mock('../lib/supabase', () => ({
  invokeSupabaseFunction: mocks.invokeSupabaseFunction,
  supabase: {},
}))

import {
  deactivateBranchSyncClient,
  listBranchSyncClients,
  listBranchSyncSetupOptions,
  registerBranchSyncClient,
} from './tenantAdminService'

describe('tenantAdminService branch sync administration', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('loads setup options through the protected tenant function', async () => {
    mocks.invokeSupabaseFunction.mockResolvedValue({
      data: {
        organizations: [
          {
            id: 'org-1',
            name: 'Ark Medical Centre',
            status: 'active',
            subscription_tier: 'pro',
          },
        ],
        branches: [{ id: 'branch-1', organization_id: 'org-1', name: 'Main' }],
      },
      error: null,
    })

    const result = await listBranchSyncSetupOptions()

    expect(mocks.invokeSupabaseFunction).toHaveBeenCalledWith('tenant-signup', {
      body: { action: 'list_branch_sync_setup_options' },
    })
    expect(result.branches).toHaveLength(1)
    expect(result.organizations[0]).toMatchObject({
      id: 'org-1',
      status: 'active',
      subscription_tier: 'pro',
    })
  })

  it('registers a machine only through the protected tenant function', async () => {
    mocks.invokeSupabaseFunction.mockResolvedValue({
      data: {
        syncClientId: 'client-1',
        organizationId: 'org-1',
        branchId: 'branch-1',
        branchSyncToken: 'generated-token',
      },
      error: null,
    })

    await registerBranchSyncClient({
      organizationId: ' org-1 ',
      branchId: ' branch-1 ',
      branchName: ' Main branch ',
      branchAutoGenerated: true,
      name: ' Main branch server ',
      branchSyncToken: ' generated-token ',
    })

    expect(mocks.invokeSupabaseFunction).toHaveBeenCalledWith('tenant-signup', {
      body: {
        action: 'register_branch_sync_client',
        organizationId: 'org-1',
        branchId: 'branch-1',
        branchName: 'Main branch',
        branchAutoGenerated: true,
        name: 'Main branch server',
        branchSyncToken: 'generated-token',
      },
    })
  })

  it('lists and deactivates clients through the protected tenant function', async () => {
    mocks.invokeSupabaseFunction
      .mockResolvedValueOnce({
        data: { clients: [{ id: 'client-1', name: 'Main branch server', isActive: true }] },
        error: null,
      })
      .mockResolvedValueOnce({
        data: { syncClientId: 'client-1', isActive: false },
        error: null,
      })

    const clients = await listBranchSyncClients(' org-1 ')
    const deactivated = await deactivateBranchSyncClient({
      organizationId: ' org-1 ',
      syncClientId: ' client-1 ',
    })

    expect(clients).toEqual([{ id: 'client-1', name: 'Main branch server', isActive: true }])
    expect(deactivated).toEqual({ syncClientId: 'client-1', isActive: false })
    expect(mocks.invokeSupabaseFunction).toHaveBeenNthCalledWith(1, 'tenant-signup', {
      body: {
        action: 'list_branch_sync_clients',
        organizationId: 'org-1',
      },
    })
    expect(mocks.invokeSupabaseFunction).toHaveBeenNthCalledWith(2, 'tenant-signup', {
      body: {
        action: 'deactivate_branch_sync_client',
        organizationId: 'org-1',
        syncClientId: 'client-1',
      },
    })
  })
})
