import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import OfflineSync from './OfflineSync'

const mocks = vi.hoisted(() => ({
  notify: vi.fn(),
  checkBranchServerUpdates: vi.fn(),
  getBranchServerConfig: vi.fn(),
  getBranchServerHealth: vi.fn(),
  getBranchSyncStatus: vi.fn(),
  getBranchUpdateStatus: vi.fn(),
  installBranchServerUpdate: vi.fn(),
  listBranchSyncSetupOptions: vi.fn(),
  listBranchSyncClients: vi.fn(),
  registerBranchSyncClient: vi.fn(),
  deactivateBranchSyncClient: vi.fn(),
}))

vi.mock('../context/AuthContext', () => ({
  useAuth: () => ({
    organization: null,
    role: 'super_admin',
    user: { id: 'user-1' },
    profile: null,
    branch: null,
  }),
}))

vi.mock('../context/NotificationContext', () => ({
  useNotification: () => ({ notify: mocks.notify }),
}))

vi.mock('../services/tenantAdminService', () => ({
  listBranchSyncSetupOptions: mocks.listBranchSyncSetupOptions,
  listBranchSyncClients: mocks.listBranchSyncClients,
  registerBranchSyncClient: mocks.registerBranchSyncClient,
  deactivateBranchSyncClient: mocks.deactivateBranchSyncClient,
}))

vi.mock('../services/branchServerApi', () => ({
  checkBranchServerUpdates: mocks.checkBranchServerUpdates,
  createNhiaBatch: vi.fn(),
  downloadNhiaBatchExport: vi.fn(),
  getBranchInventory: vi.fn(),
  getBranchServerConfig: mocks.getBranchServerConfig,
  getBranchServerHealth: mocks.getBranchServerHealth,
  getSavedBranchToken: vi.fn(() => ''),
  getBranchSyncStatus: mocks.getBranchSyncStatus,
  getBranchUpdateStatus: mocks.getBranchUpdateStatus,
  getNhiaSummary: vi.fn(async () => null),
  listNhiaClaims: vi.fn(async () => []),
  installBranchServerUpdate: mocks.installBranchServerUpdate,
  pullBranchInventory: vi.fn(),
  pullBranchReferenceData: vi.fn(),
  repairBranchSync: vi.fn(),
  runBranchSync: vi.fn(),
  saveBranchToken: vi.fn((token) => token),
  submitPendingNhiaClaims: vi.fn(),
}))

vi.mock('../services/nhisService', () => ({
  getNhiaApiSettings: vi.fn(async () => null),
  saveNhiaApiSettings: vi.fn(),
}))

vi.mock('../services/offlinePosCache', () => ({
  saveOfflinePosSnapshot: vi.fn(),
}))

describe('OfflineSync branch registration', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mocks.getBranchServerConfig.mockReturnValue({ enabled: false, token: '', url: '' })
    mocks.listBranchSyncSetupOptions.mockResolvedValue({
      organizations: [
        {
          id: 'org-1',
          name: 'Ark Medical Centre',
          subdomain: 'ark',
          status: 'active',
        },
      ],
      branches: [
        {
          id: 'branch-1',
          organization_id: 'org-1',
          name: 'Ark Main',
          code: 'MAIN',
        },
      ],
    })
    mocks.listBranchSyncClients.mockResolvedValue([
      {
        id: 'client-existing',
        name: 'Dispensary server',
        branchId: 'branch-1',
        branchName: 'Ark Main',
        branchCode: 'MAIN',
        isActive: true,
        lastSeenAt: null,
      },
    ])
    mocks.registerBranchSyncClient.mockResolvedValue({
      syncClientId: 'client-new',
      organizationId: 'org-1',
      branchId: 'branch-1',
      branchSyncToken: 'sync-token-returned-by-server',
    })
  })

  it('registers the selected facility machine and displays a complete one-time environment block', async () => {
    render(<OfflineSync />)

    await screen.findByText('Dispensary server')
    fireEvent.change(screen.getByLabelText('Branch sync token'), {
      target: { value: 'a'.repeat(32) },
    })
    fireEvent.click(screen.getByRole('button', { name: 'Register Sync Client' }))

    await waitFor(() => {
      expect(mocks.registerBranchSyncClient).toHaveBeenCalledWith(
        expect.objectContaining({
          organizationId: 'org-1',
          branchId: 'branch-1',
          branchAutoGenerated: false,
          name: 'Main branch server',
          branchSyncToken: 'a'.repeat(32),
        })
      )
    })

    const setupBlock = await screen.findByText(/PORT=4780/)
    expect(setupBlock).not.toHaveTextContent('BRANCH_SERVER_TOKEN=')
    expect(setupBlock).toHaveTextContent('NHIA_CONFIG_SECRET_KEY=')
    expect(setupBlock).toHaveTextContent('ORGANIZATION_ID=org-1')
    expect(setupBlock).toHaveTextContent('BRANCH_ID=branch-1')
    expect(setupBlock).toHaveTextContent('BRANCH_SYNC_TOKEN=sync-token-returned-by-server')
    expect(setupBlock).toHaveTextContent('SUPABASE_URL=')
    expect(setupBlock).toHaveTextContent('SUPABASE_SYNC_KEY=')
  })

  it('checks and starts a signed localhost update from the admin controls', async () => {
    mocks.getBranchServerConfig.mockReturnValue({
      enabled: true,
      token: 'branch-token',
      url: 'http://localhost:4780',
    })
    mocks.getBranchServerHealth.mockResolvedValue({ ok: true, version: '1.0.0' })
    mocks.getBranchSyncStatus.mockResolvedValue({})
    mocks.getBranchUpdateStatus.mockResolvedValue({
      configured: true,
      currentVersion: '1.0.0',
      latestVersion: '1.1.0',
      channel: 'stable',
      state: 'available',
      available: true,
      platform: 'linux',
      installerSupported: true,
      installerReady: true,
      message: 'HealthFlow 1.1.0 is available.',
    })
    mocks.checkBranchServerUpdates.mockResolvedValue({
      configured: true,
      currentVersion: '1.0.0',
      latestVersion: '1.1.0',
      channel: 'stable',
      state: 'available',
      available: true,
      platform: 'linux',
      installerSupported: true,
      installerReady: true,
      message: 'HealthFlow 1.1.0 is available.',
    })
    mocks.installBranchServerUpdate.mockResolvedValue({
      state: 'installing',
      restartRequired: true,
    })
    vi.spyOn(window, 'confirm').mockReturnValue(true)

    render(<OfflineSync />)

    expect(screen.getByRole('heading', { name: 'Install HealthFlow on this Computer' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Download and Install' })).toBeInTheDocument()
    await screen.findByText('HealthFlow 1.1.0 is available.')
    fireEvent.click(screen.getByRole('button', { name: 'Check for Updates' }))
    await waitFor(() => expect(mocks.checkBranchServerUpdates).toHaveBeenCalledTimes(1))

    fireEvent.click(screen.getByRole('button', { name: 'Download Update' }))
    await waitFor(() => expect(mocks.installBranchServerUpdate).toHaveBeenCalledTimes(1))
    expect(mocks.notify).toHaveBeenCalledWith(
      'Update installation started. The localhost app will restart briefly.',
      'success'
    )
  })
})
