import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import OfflineSync from './OfflineSync'

const mocks = vi.hoisted(() => ({
  notify: vi.fn(),
  checkBranchServerUpdates: vi.fn(),
  getBranchServerConfig: vi.fn(),
  getBranchServerHealth: vi.fn(),
  getBranchSyncStatus: vi.fn(),
  getBranchUpdateStatus: vi.fn(),
  installBranchServerUpdate: vi.fn(),
  listBranchSyncSetupOptions: vi.fn(),
  listBranchSyncClients: vi.fn(),
  registerBranchSyncClient: vi.fn(),
  deactivateBranchSyncClient: vi.fn(),
}))

vi.mock('../context/AuthContext', () => ({
  useAuth: () => ({
    organization: null,
    role: 'super_admin',
    user: { id: 'user-1' },
    profile: null,
    branch: null,
  }),
}))

vi.mock('../context/NotificationContext', () => ({
  useNotification: () => ({ notify: mocks.notify }),
}))

vi.mock('../services/tenantAdminService', () => ({
  listBranchSyncSetupOptions: mocks.listBranchSyncSetupOptions,
  listBranchSyncClients: mocks.listBranchSyncClients,
  registerBranchSyncClient: mocks.registerBranchSyncClient,
  deactivateBranchSyncClient: mocks.deactivateBranchSyncClient,
}))

vi.mock('../services/branchServerApi', () => ({
  checkBranchServerUpdates: mocks.checkBranchServerUpdates,
  createNhiaBatch: vi.fn(),
  downloadNhiaBatchExport: vi.fn(),
  getBranchInventory: vi.fn(),
  getBranchServerConfig: mocks.getBranchServerConfig,
  getBranchServerHealth: mocks.getBranchServerHealth,
  getSavedBranchToken: vi.fn(() => ''),
  getBranchSyncStatus: mocks.getBranchSyncStatus,
  getBranchUpdateStatus: mocks.getBranchUpdateStatus,
  getNhiaSummary: vi.fn(async () => null),
  listNhiaClaims: vi.fn(async () => []),
  installBranchServerUpdate: mocks.installBranchServerUpdate,
  pullBranchInventory: vi.fn(),
  pullBranchReferenceData: vi.fn(),
  repairBranchSync: vi.fn(),
  runBranchSync: vi.fn(),
  saveBranchToken: vi.fn((token) => token),
  submitPendingNhiaClaims: vi.fn(),
}))

vi.mock('../services/nhisService', () => ({
  getNhiaApiSettings: vi.fn(async () => null),
  saveNhiaApiSettings: vi.fn(),
}))

vi.mock('../services/offlinePosCache', () => ({
  saveOfflinePosSnapshot: vi.fn(),
}))

describe('OfflineSync branch registration', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mocks.getBranchServerConfig.mockReturnValue({ enabled: false, token: '', url: '' })
    mocks.listBranchSyncSetupOptions.mockResolvedValue({
      organizations: [
        {
          id: 'org-1',
          name: 'Ark Medical Centre',
          subdomain: 'ark',
          status: 'active',
        },
      ],
      branches: [
        {
          id: 'branch-1',
          organization_id: 'org-1',
          name: 'Ark Main',
          code: 'MAIN',
        },
      ],
    })
    mocks.listBranchSyncClients.mockResolvedValue([
      {
        id: 'client-existing',
        name: 'Dispensary server',
        branchId: 'branch-1',
        branchName: 'Ark Main',
        branchCode: 'MAIN',
        isActive: true,
        lastSeenAt: null,
      },
    ])
    mocks.registerBranchSyncClient.mockResolvedValue({
      syncClientId: 'client-new',
      organizationId: 'org-1',
      branchId: 'branch-1',
      branchSyncToken: 'sync-token-returned-by-server',
    })
  })

  it('registers the selected facility machine and displays a complete one-time environment block', async () => {
    render(<OfflineSync />)

    await screen.findByText('Dispensary server')
    fireEvent.change(screen.getByLabelText('Branch sync token'), {
      target: { value: 'a'.repeat(32) },
    })
    fireEvent.click(screen.getByRole('button', { name: 'Register Sync Client' }))

    await waitFor(() => {
      expect(mocks.registerBranchSyncClient).toHaveBeenCalledWith(
        expect.objectContaining({
          organizationId: 'org-1',
          branchId: 'branch-1',
          branchAutoGenerated: false,
          name: 'Main branch server',
          branchSyncToken: 'a'.repeat(32),
        })
      )
    })

    const setupBlock = await screen.findByText(/PORT=4780/)
    expect(setupBlock).not.toHaveTextContent('BRANCH_SERVER_TOKEN=')
    expect(setupBlock).toHaveTextContent('NHIA_CONFIG_SECRET_KEY=')
    expect(setupBlock).toHaveTextContent('ORGANIZATION_ID=org-1')
    expect(setupBlock).toHaveTextContent('BRANCH_ID=branch-1')
    expect(setupBlock).toHaveTextContent('BRANCH_SYNC_TOKEN=sync-token-returned-by-server')
    expect(setupBlock).toHaveTextContent('SUPABASE_URL=')
    expect(setupBlock).toHaveTextContent('SUPABASE_SYNC_KEY=')
  })

  it('checks and starts a signed localhost update from the admin controls', async () => {
    mocks.getBranchServerConfig.mockReturnValue({
      enabled: true,
      token: 'branch-token',
      url: 'http://localhost:4780',
    })
    mocks.getBranchServerHealth.mockResolvedValue({ ok: true, version: '1.0.0' })
    mocks.getBranchSyncStatus.mockResolvedValue({})
    mocks.getBranchUpdateStatus.mockResolvedValue({
      configured: true,
      currentVersion: '1.0.0',
      latestVersion: '1.1.0',
      channel: 'stable',
      state: 'available',
      available: true,
      platform: 'linux',
      installerSupported: true,
      installerReady: true,
      message: 'HealthFlow 1.1.0 is available.',
    })
    mocks.checkBranchServerUpdates.mockResolvedValue({
      configured: true,
      currentVersion: '1.0.0',
      latestVersion: '1.1.0',
      channel: 'stable',
      state: 'available',
      available: true,
      platform: 'linux',
      installerSupported: true,
      installerReady: true,
      message: 'HealthFlow 1.1.0 is available.',
    })
    mocks.installBranchServerUpdate.mockResolvedValue({
      state: 'installing',
      restartRequired: true,
    })
    vi.spyOn(window, 'confirm').mockReturnValue(true)

    render(<OfflineSync />)

    expect(screen.getByRole('heading', { name: 'Install HealthFlow on this Computer' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Download and Install' })).toBeInTheDocument()
    await screen.findByText('HealthFlow 1.1.0 is available.')
    fireEvent.click(screen.getByRole('button', { name: 'Check for Updates' }))
    await waitFor(() => expect(mocks.checkBranchServerUpdates).toHaveBeenCalledTimes(1))

    fireEvent.click(screen.getByRole('button', { name: 'Download Update' }))
    await waitFor(() => expect(mocks.installBranchServerUpdate).toHaveBeenCalledTimes(1))
    expect(mocks.notify).toHaveBeenCalledWith(
      'Update installation started. The localhost app will restart briefly.',
      'success'
    )
  })

  const NOT_CONFIGURED_MESSAGE =
    'The HealthFlow Offline installer has not been configured for this environment. Contact system administration.'
  const CONFIGURED_INSTALLER_URL = 'https://cdn.healthflowgh.com/releases/HealthFlow-Offline-2.4.0.zip'

  afterEach(() => {
    vi.unstubAllEnvs()
  })

  it('refuses to open the installer when no environment variable is configured (default state)', async () => {
    // No vi.stubEnv call: this exercises the real current default, where
    // VITE_HEALTHFLOW_INSTALLER_URL is unset in this repository.
    const fetchMock = vi.fn()
    vi.stubGlobal('fetch', fetchMock)
    const openSpy = vi.spyOn(window, 'open').mockImplementation(() => null)

    render(<OfflineSync />)

    fireEvent.click(screen.getByRole('button', { name: 'Download and Install' }))

    await waitFor(() => expect(mocks.notify).toHaveBeenCalledWith(NOT_CONFIGURED_MESSAGE, 'error'))
    expect(openSpy).not.toHaveBeenCalled()
    expect(fetchMock).not.toHaveBeenCalled()
  })

  it('refuses to open the installer when the environment variable is an empty string', async () => {
    vi.resetModules()
    vi.stubEnv('VITE_HEALTHFLOW_INSTALLER_URL', '')
    const { default: FreshOfflineSync } = await import('./OfflineSync')
    const openSpy = vi.spyOn(window, 'open').mockImplementation(() => null)

    render(<FreshOfflineSync />)

    fireEvent.click(screen.getByRole('button', { name: 'Download and Install' }))

    await waitFor(() => expect(mocks.notify).toHaveBeenCalledWith(NOT_CONFIGURED_MESSAGE, 'error'))
    expect(openSpy).not.toHaveBeenCalled()
  })

  it('refuses to open the installer when the environment variable equals the known placeholder', async () => {
    vi.resetModules()
    vi.stubEnv(
      'VITE_HEALTHFLOW_INSTALLER_URL',
      'https://healthflowcloud.com/downloads/HealthFlow-Installer.zip'
    )
    const { default: FreshOfflineSync } = await import('./OfflineSync')
    const openSpy = vi.spyOn(window, 'open').mockImplementation(() => null)

    render(<FreshOfflineSync />)

    fireEvent.click(screen.getByRole('button', { name: 'Download and Install' }))

    await waitFor(() => expect(mocks.notify).toHaveBeenCalledWith(NOT_CONFIGURED_MESSAGE, 'error'))
    expect(openSpy).not.toHaveBeenCalled()
  })

  it('refuses to open a configured but malformed installer URL', async () => {
    vi.resetModules()
    vi.stubEnv('VITE_HEALTHFLOW_INSTALLER_URL', 'not a url')
    const { default: FreshOfflineSync } = await import('./OfflineSync')
    const openSpy = vi.spyOn(window, 'open').mockImplementation(() => null)

    render(<FreshOfflineSync />)

    fireEvent.click(screen.getByRole('button', { name: 'Download and Install' }))

    await waitFor(() => expect(mocks.notify).toHaveBeenCalledWith(NOT_CONFIGURED_MESSAGE, 'error'))
    expect(openSpy).not.toHaveBeenCalled()
  })

  it('refuses to open a configured installer URL using an unsafe protocol', async () => {
    vi.resetModules()
    vi.stubEnv('VITE_HEALTHFLOW_INSTALLER_URL', 'http://cdn.healthflowgh.com/HealthFlow-Offline.zip')
    const { default: FreshOfflineSync } = await import('./OfflineSync')
    const openSpy = vi.spyOn(window, 'open').mockImplementation(() => null)

    render(<FreshOfflineSync />)

    fireEvent.click(screen.getByRole('button', { name: 'Download and Install' }))

    await waitFor(() => expect(mocks.notify).toHaveBeenCalledWith(NOT_CONFIGURED_MESSAGE, 'error'))
    expect(openSpy).not.toHaveBeenCalled()
  })

  it('opens an explicitly configured, reachable installer URL (existing working behavior unchanged)', async () => {
    vi.resetModules()
    vi.stubEnv('VITE_HEALTHFLOW_INSTALLER_URL', CONFIGURED_INSTALLER_URL)
    const { default: FreshOfflineSync } = await import('./OfflineSync')
    const fetchMock = vi.fn().mockResolvedValue(new Response(null, { status: 200 }))
    vi.stubGlobal('fetch', fetchMock)
    const openSpy = vi.spyOn(window, 'open').mockImplementation(() => null)

    render(<FreshOfflineSync />)

    fireEvent.click(screen.getByRole('button', { name: 'Download and Install' }))

    await waitFor(() => expect(openSpy).toHaveBeenCalledTimes(1))
    expect(openSpy).toHaveBeenCalledWith(CONFIGURED_INSTALLER_URL, '_blank', 'noopener,noreferrer')
    expect(fetchMock).toHaveBeenCalledWith(CONFIGURED_INSTALLER_URL, expect.objectContaining({ method: 'HEAD' }))
    expect(mocks.notify).not.toHaveBeenCalledWith(NOT_CONFIGURED_MESSAGE, 'error')
    expect(mocks.notify).not.toHaveBeenCalledWith(
      'Installer availability could not be verified before opening. Proceeding with the configured download.',
      'warning'
    )
  })

  it('does not open an explicitly configured installer URL that returns 404', async () => {
    vi.resetModules()
    vi.stubEnv('VITE_HEALTHFLOW_INSTALLER_URL', CONFIGURED_INSTALLER_URL)
    const { default: FreshOfflineSync } = await import('./OfflineSync')
    const fetchMock = vi.fn().mockResolvedValue(new Response(null, { status: 404 }))
    vi.stubGlobal('fetch', fetchMock)
    const openSpy = vi.spyOn(window, 'open').mockImplementation(() => null)

    render(<FreshOfflineSync />)

    fireEvent.click(screen.getByRole('button', { name: 'Download and Install' }))

    await waitFor(() =>
      expect(mocks.notify).toHaveBeenCalledWith(
        'The installer package could not be found at the configured location. Contact system administration.',
        'error'
      )
    )
    expect(openSpy).not.toHaveBeenCalled()
  })

  it('does not open an explicitly configured installer URL that returns 410', async () => {
    vi.resetModules()
    vi.stubEnv('VITE_HEALTHFLOW_INSTALLER_URL', CONFIGURED_INSTALLER_URL)
    const { default: FreshOfflineSync } = await import('./OfflineSync')
    const fetchMock = vi.fn().mockResolvedValue(new Response(null, { status: 410 }))
    vi.stubGlobal('fetch', fetchMock)
    const openSpy = vi.spyOn(window, 'open').mockImplementation(() => null)

    render(<FreshOfflineSync />)

    fireEvent.click(screen.getByRole('button', { name: 'Download and Install' }))

    await waitFor(() =>
      expect(mocks.notify).toHaveBeenCalledWith(
        'The installer package could not be found at the configured location. Contact system administration.',
        'error'
      )
    )
    expect(openSpy).not.toHaveBeenCalled()
  })

  it.each([405, 401, 403, 408, 409, 425, 429, 500, 502, 503])(
    'treats HTTP %i as inconclusive — opens the installer with a warning instead of blocking it',
    async (status) => {
      vi.resetModules()
      vi.stubEnv('VITE_HEALTHFLOW_INSTALLER_URL', CONFIGURED_INSTALLER_URL)
      const { default: FreshOfflineSync } = await import('./OfflineSync')
      const fetchMock = vi.fn().mockResolvedValue(new Response(null, { status }))
      vi.stubGlobal('fetch', fetchMock)
      const openSpy = vi.spyOn(window, 'open').mockImplementation(() => null)

      render(<FreshOfflineSync />)

      fireEvent.click(screen.getByRole('button', { name: 'Download and Install' }))

      await waitFor(() => expect(openSpy).toHaveBeenCalledTimes(1))
      expect(openSpy).toHaveBeenCalledWith(CONFIGURED_INSTALLER_URL, '_blank', 'noopener,noreferrer')
      expect(mocks.notify).toHaveBeenCalledWith(
        'Installer availability could not be verified before opening. Proceeding with the configured download.',
        'warning'
      )
      expect(mocks.notify).not.toHaveBeenCalledWith(
        'The installer package could not be found at the configured location. Contact system administration.',
        'error'
      )
    }
  )

  it('opens an explicitly configured installer URL when the check is inconclusive, and says so', async () => {
    vi.resetModules()
    vi.stubEnv('VITE_HEALTHFLOW_INSTALLER_URL', CONFIGURED_INSTALLER_URL)
    const { default: FreshOfflineSync } = await import('./OfflineSync')
    const fetchMock = vi.fn().mockRejectedValue(new TypeError('Failed to fetch'))
    vi.stubGlobal('fetch', fetchMock)
    const openSpy = vi.spyOn(window, 'open').mockImplementation(() => null)

    render(<FreshOfflineSync />)

    fireEvent.click(screen.getByRole('button', { name: 'Download and Install' }))

    await waitFor(() => expect(openSpy).toHaveBeenCalledTimes(1))
    expect(openSpy).toHaveBeenCalledWith(CONFIGURED_INSTALLER_URL, '_blank', 'noopener,noreferrer')
    expect(mocks.notify).toHaveBeenCalledWith(
      'Installer availability could not be verified before opening. Proceeding with the configured download.',
      'warning'
    )
  })
})
