import { useMemo, useState } from 'react'
import { Link, NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import { Activity, BarChart3, Boxes, ClipboardCheck, FileText, Menu, Pill, ShoppingCart, Users, Wifi, X } from 'lucide-react'
import './LiveDemo.css'

const products = [{ id: 1, name: 'Artemether / Lumefantrine', strength: '20/120 mg', price: 34.5, stock: 42, category: 'Antimalarial' }, { id: 2, name: 'Paracetamol', strength: '500 mg', price: 8, stock: 184, category: 'Analgesic' }, { id: 3, name: 'Amoxicillin', strength: '500 mg', price: 22, stock: 9, category: 'Antibiotic' }, { id: 4, name: 'ORS Sachets', strength: '200 ml', price: 6.5, stock: 0, category: 'Wellness' }]
const nav = [['dashboard', 'Dashboard', BarChart3], ['pos', 'Point of Sale', ShoppingCart], ['inventory', 'Inventory', Boxes], ['nhis', 'NHIS Claims', ClipboardCheck], ['patients', 'Patients', Users], ['reports', 'Reports', FileText], ['staff', 'Staff', Users], ['offline', 'Offline Mode', Wifi], ['settings', 'Settings', Activity]]
const money = (value) => `GHS ${Number(value).toLocaleString('en-GH', { minimumFractionDigits: 2 })}`

function DemoLayout() {
  const [cart, setCart] = useState([]); const [query, setQuery] = useState(''); const [offline, setOffline] = useState(false); const [syncing, setSyncing] = useState(false); const [menu, setMenu] = useState(false); const [tour, setTour] = useState(true); const navigate = useNavigate()
  const add = (p) => setCart(c => c.some(x => x.id === p.id) ? c.map(x => x.id === p.id ? { ...x, qty: x.qty + 1 } : x) : [...c, { ...p, qty: 1 }])
  const total = useMemo(() => cart.reduce((s, x) => s + x.price * x.qty, 0), [cart])
  const reset = () => { setCart([]); setQuery(''); setOffline(false); setSyncing(false) }
  const ctx = { cart, setCart, query, setQuery, offline, setOffline, syncing, setSyncing, add, total, reset, navigate }
  return <div className="demo-app"><aside className={menu ? 'demo-sidebar open' : 'demo-sidebar'}><div className="demo-brand"><Pill /> <span>HealthFlow <b>DEMO</b></span><button aria-label="Close menu" onClick={() => setMenu(false)}><X /></button></div><p className="demo-facility">HealthFlow Demo Pharmacy<br /><small>Accra · Main Branch</small></p><nav>{nav.map(([id, label, Icon]) => <NavLink key={id} to={`/demo/${id}`} onClick={() => setMenu(false)}><Icon />{label}</NavLink>)}</nav><div className="demo-side-bottom"><button onClick={reset}>Reset Demo</button><a href="mailto:hello@healthflow.demo">Get HealthFlow</a></div></aside><main><header className="demo-top"><button className="demo-menu" onClick={() => setMenu(true)} aria-label="Open menu"><Menu /></button><span className="demo-pill">LIVE DEMO · Demo Environment</span><span className={offline ? 'demo-network offline' : 'demo-network'}>{syncing ? 'Synchronizing' : offline ? 'Offline — Local Server' : 'Online'}</span><span className="demo-user">DA<br /><small>Demo Administrator</small></span><Link to="/login">Exit Demo</Link></header>{tour && <section className="demo-tour"><div><strong>Welcome to HealthFlow</strong><span>Explore sales, inventory, NHIS claims, reports and offline operations.</span></div><button onClick={() => { setTour(false); navigate('/demo/pos') }}>Start Tour</button><button className="quiet" onClick={() => setTour(false)}>Explore myself</button></section>}<Routes><Route index element={<Welcome />} /><Route path="dashboard" element={<Dashboard ctx={ctx} />} /><Route path="pos" element={<POS ctx={ctx} />} /><Route path="inventory" element={<Inventory ctx={ctx} />} /><Route path="nhis" element={<Nhis />} /><Route path="patients" element={<Patients />} /><Route path="reports" element={<Reports />} /><Route path="staff" element={<Staff />} /><Route path="offline" element={<Offline ctx={ctx} />} /><Route path="settings" element={<Settings />} /><Route path="*" element={<Navigate to="/demo/dashboard" replace />} /></Routes></main></div>
}
function Welcome(){ return <section className="demo-welcome"><Pill /><h1>HealthFlow Pharmacy</h1><p>Run your pharmacy smarter.</p><Link className="demo-primary" to="/demo/dashboard">Start Live Demo</Link><small>No account required. Demo data only.</small></section> }
function Dashboard({ctx}) { return <Page title="Good morning, Demo Administrator" subtitle="Here is your pharmacy at a glance."><div className="demo-stats">{[['Today’s Sales', money(4860.5)], ['Transactions', '84'], ['NHIS Claims', '27'], ['Low Stock', '6']].map(x => <article key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>Demo data</small></article>)}</div><div className="demo-grid"><section className="demo-card wide"><h2>Sales trend</h2><div className="demo-chart">{[42,65,48,79,58,90,72].map((n,i)=><i key={i} style={{height:`${n}%`}} />)}</div></section><section className="demo-card"><h2>Explore HealthFlow</h2><button onClick={()=>ctx.navigate('/demo/pos')}>Make a Sale</button><button onClick={()=>ctx.navigate('/demo/nhis')}>Create NHIS Claim</button><button onClick={()=>ctx.navigate('/demo/offline')}>See Offline Mode</button></section></div></Page> }
function POS({ctx}) { const [done,setDone]=useState(false); const list=products.filter(p=>p.name.toLowerCase().includes(ctx.query.toLowerCase())); return <Page title="Point of Sale" subtitle="Complete a simulated sale with fictional products."><div className="demo-pos"><section><input aria-label="Search medicines" placeholder="Search medicines or scan barcode" value={ctx.query} onChange={e=>ctx.setQuery(e.target.value)} /><div className="demo-products">{list.map(p=><article key={p.id}><Pill /><strong>{p.name}</strong><small>{p.strength} · {p.stock ? `${p.stock} in stock` : 'Out of stock'}</small><b>{money(p.price)}</b><button disabled={!p.stock} onClick={()=>ctx.add(p)}>Add</button></article>)}</div></section><aside className="demo-cart"><h2>Current sale</h2>{ctx.cart.length ? ctx.cart.map(x=><p key={x.id}>{x.qty} × {x.name}<b>{money(x.qty*x.price)}</b></p>) : <p>Your cart is ready for demo items.</p>}<strong>Total {money(ctx.total)}</strong><button className="demo-primary" disabled={!ctx.cart.length} onClick={()=>setDone(true)}>Complete Demo Sale</button>{done&&<div className="demo-success"><strong>Demo Sale Completed</strong><p>Receipt DEMO-2026-084 created. No payment was processed.</p></div>}</aside></div></Page> }
function Inventory({ctx}){ const [adjusted,setAdjusted]=useState(false); return <Page title="Inventory" subtitle="Fictional stock. Changes remain in this browser only."><div className="demo-card"><input aria-label="Search inventory" placeholder="Search inventory" value={ctx.query} onChange={e=>ctx.setQuery(e.target.value)} /><table><thead><tr><th>Medicine</th><th>Strength</th><th>Stock</th><th>Selling price</th><th>Status</th><th /></tr></thead><tbody>{products.filter(p=>p.name.toLowerCase().includes(ctx.query.toLowerCase())).map(p=><tr key={p.id}><td>{p.name}</td><td>{p.strength}</td><td>{p.stock}</td><td>{money(p.price)}</td><td><span className={p.stock===0?'danger':p.stock<12?'warn':'ok'}>{p.stock===0?'Out of Stock':p.stock<12?'Low Stock':'In Stock'}</span></td><td><button onClick={()=>setAdjusted(true)}>Adjust</button></td></tr>)}</tbody></table>{adjusted&&<p className="demo-success">Demo stock adjustment saved locally.</p>}</div></Page> }
function Nhis(){ const [ccc,setCcc]=useState(''); const valid=/^\d{5}$/.test(ccc); return <Page title="NHIS Claims" subtitle="Explore fictional claims and all-at-once readiness checks."><div className="demo-grid"><section className="demo-card wide"><h2>Claim · DEMO-NHIS-027</h2><p><b>Patient:</b> Ama Example · Demo membership GH-DEMO-1027</p><p>Malaria · Artemether/Lumefantrine 20/120 mg · 2 tablets twice daily for 3 days</p><p><b>Claim total:</b> {money(103.5)}</p><label>CCC Code <input aria-label="CCC Code" value={ccc} onChange={e=>setCcc(e.target.value.replace(/\D/g,'').slice(0,5))} placeholder="Enter 5 digits" /></label><div className={valid?'demo-success':'demo-blocker'}>{valid?'✓ CCC Code accepted. Claim is ready for simulated export.':'CCC Code is required before this claim can be completed.'}</div></section><section className="demo-card"><h2>Claim readiness</h2>{['Patient information','Diagnosis','Medicines','Duration','Tariff','Attachments',valid?'CCC Code':'CCC Code required'].map((x,i)=><p key={x} className={i===6&&!valid?'warn':'ok'}>{i===6&&!valid?'⚠':'✓'} {x}</p>)}<small>Demo only — no NHIA or CLAIM-it request is made.</small></section></div></Page> }
const Patients=()=> <Page title="Patients" subtitle="Fictional profiles only."><div className="demo-card"><h2>Example patient profiles</h2>{['Ama Example','Kojo Demonstration','Esi Sample'].map((x,i)=><p key={x}><b>{x}</b> · Demo patient {i+101} · Recent medicines and claim history available</p>)}</div></Page>
const Reports=()=> <Page title="Reports" subtitle="Demo analytics for Today, This Week and This Month."><div className="demo-grid"><section className="demo-card wide"><h2>Payment breakdown</h2><div className="demo-chart">{[73,45,61,35,52].map((n,i)=><i key={i} style={{height:`${n}%`}} />)}</div></section><section className="demo-card"><h2>Top medicines</h2><p>Paracetamol · 126 units</p><p>Artemether/Lumefantrine · 68 units</p><p>ORS Sachets · 53 units</p></section></div></Page>
const Staff=()=> <Page title="Staff" subtitle="Demo roles and activity."><div className="demo-card">{['Demo Administrator','Demo Pharmacist','Demo Claims Officer','Demo Cashier'].map((x,i)=><p key={x}><b>{x}</b><span> Main Branch · Active</span><small>{['Administrator','Pharmacist','Claims Officer','Cashier'][i]}</small></p>)}</div></Page>
function Offline({ctx}){ const restore=()=>{ctx.setSyncing(true);setTimeout(()=>{ctx.setOffline(false);ctx.setSyncing(false)},900)}; return <Page title="Offline Mode" subtitle="A simulated preview. It never changes your network or starts a local server."><div className="demo-stats"><article><span>Main Computer</span><strong>✓ Connected</strong></article><article><span>Offline Data</span><strong>✓ Ready</strong></article><article><span>Staff Access</span><strong>6 Ready · 2 Need PIN</strong></article><article><span>Unsynced Work</span><strong>{ctx.offline?'1 queued':'0'}</strong></article></div><section className="demo-card"><h2>Offline Mode Ready</h2><p>Production Verification: Not Completed</p>{ctx.offline?<><div className="demo-blocker">Internet is unavailable. HealthFlow is using the facility’s Main Computer. Supported demo work is queued locally.</div><button className="demo-primary" onClick={restore}>Restore Internet</button></>:<button className="demo-primary" onClick={()=>ctx.setOffline(true)}>Simulate Internet Outage</button>}<button onClick={()=>alert('Preview only: a real facility verifies an outage, local work, reconnection and reconciliation.')}>Preview Production Verification</button></section></Page> }
const Settings=()=> <Page title="Settings" subtitle="Demo-only preferences."><div className="demo-card"><h2>HealthFlow Demo Pharmacy</h2><p>Receipt preferences, NHIS settings and staff roles are examples only. External settings are unavailable in the public demo.</p></div></Page>
function Page({title,subtitle,children}){return <section className="demo-page"><div className="demo-page-title"><div><h1>{title}</h1><p>{subtitle}</p></div></div>{children}</section>}
export default function LiveDemo(){ return <DemoLayout /> }
