export const PLATFORM_NAME = 'HealthFlow'
export const PLATFORM_GENERATED_BY = 'Generated by HealthFlow\u00AE'
export const DEFAULT_FACILITY_NAME = 'Facility'

export const getFacilityName = (source = {}) =>
  String(
    source?.facility_name ||
      source?.facilityName ||
      source?.pharmacy_name ||
      source?.pharmacyName ||
      source?.name ||
      DEFAULT_FACILITY_NAME
  ).trim() || DEFAULT_FACILITY_NAME

export const getFacilityLogo = (source = {}) =>
  String(
    source?.facility_logo ||
      source?.facilityLogo ||
      source?.logo_url ||
      source?.logoUrl ||
      ''
  ).trim()

export const getFacilityWebsite = (source = {}) =>
  String(source?.website || source?.facility_website || source?.facilityWebsite || '').trim()

export const getReceiptFooter = (source = {}) =>
  String(source?.receipt_footer || source?.receiptFooter || '').trim()

export const getReportFooter = (source = {}) =>
  String(source?.report_footer || source?.reportFooter || '').trim()
